//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrainingCompany.Web.ChatbotService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ChatResponse", Namespace="http://trainingcompany.com/")]
    [System.SerializableAttribute()]
    public partial class ChatResponse : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private bool SuccessField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ResponseField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IntentField;
        
        private decimal ConfidenceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ActionTypeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public bool Success {
            get {
                return this.SuccessField;
            }
            set {
                if ((this.SuccessField.Equals(value) != true)) {
                    this.SuccessField = value;
                    this.RaisePropertyChanged("Success");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Response {
            get {
                return this.ResponseField;
            }
            set {
                if ((object.ReferenceEquals(this.ResponseField, value) != true)) {
                    this.ResponseField = value;
                    this.RaisePropertyChanged("Response");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Intent {
            get {
                return this.IntentField;
            }
            set {
                if ((object.ReferenceEquals(this.IntentField, value) != true)) {
                    this.IntentField = value;
                    this.RaisePropertyChanged("Intent");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public decimal Confidence {
            get {
                return this.ConfidenceField;
            }
            set {
                if ((this.ConfidenceField.Equals(value) != true)) {
                    this.ConfidenceField = value;
                    this.RaisePropertyChanged("Confidence");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string ActionType {
            get {
                return this.ActionTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.ActionTypeField, value) != true)) {
                    this.ActionTypeField = value;
                    this.RaisePropertyChanged("ActionType");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfString", Namespace="http://trainingcompany.com/", ItemName="string")]
    [System.SerializableAttribute()]
    public class ArrayOfString : System.Collections.Generic.List<string> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CourseRecommendation", Namespace="http://trainingcompany.com/")]
    [System.SerializableAttribute()]
    public partial class CourseRecommendation : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int CourseIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TitleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        private decimal PriceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ModeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int CourseID {
            get {
                return this.CourseIDField;
            }
            set {
                if ((this.CourseIDField.Equals(value) != true)) {
                    this.CourseIDField = value;
                    this.RaisePropertyChanged("CourseID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Title {
            get {
                return this.TitleField;
            }
            set {
                if ((object.ReferenceEquals(this.TitleField, value) != true)) {
                    this.TitleField = value;
                    this.RaisePropertyChanged("Title");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public decimal Price {
            get {
                return this.PriceField;
            }
            set {
                if ((this.PriceField.Equals(value) != true)) {
                    this.PriceField = value;
                    this.RaisePropertyChanged("Price");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string Mode {
            get {
                return this.ModeField;
            }
            set {
                if ((object.ReferenceEquals(this.ModeField, value) != true)) {
                    this.ModeField = value;
                    this.RaisePropertyChanged("Mode");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://trainingcompany.com/", ConfigurationName="ChatbotService.ChatbotServiceSoap")]
    public interface ChatbotServiceSoap {
        
        // CODEGEN: Generating message contract since element name userMessage from namespace http://trainingcompany.com/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://trainingcompany.com/ProcessMessage", ReplyAction="*")]
        TrainingCompany.Web.ChatbotService.ProcessMessageResponse ProcessMessage(TrainingCompany.Web.ChatbotService.ProcessMessageRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://trainingcompany.com/ProcessMessage", ReplyAction="*")]
        System.Threading.Tasks.Task<TrainingCompany.Web.ChatbotService.ProcessMessageResponse> ProcessMessageAsync(TrainingCompany.Web.ChatbotService.ProcessMessageRequest request);
        
        // CODEGEN: Generating message contract since element name GetQuickRepliesResult from namespace http://trainingcompany.com/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://trainingcompany.com/GetQuickReplies", ReplyAction="*")]
        TrainingCompany.Web.ChatbotService.GetQuickRepliesResponse GetQuickReplies(TrainingCompany.Web.ChatbotService.GetQuickRepliesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://trainingcompany.com/GetQuickReplies", ReplyAction="*")]
        System.Threading.Tasks.Task<TrainingCompany.Web.ChatbotService.GetQuickRepliesResponse> GetQuickRepliesAsync(TrainingCompany.Web.ChatbotService.GetQuickRepliesRequest request);
        
        // CODEGEN: Generating message contract since element name GetCourseRecommendationsResult from namespace http://trainingcompany.com/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://trainingcompany.com/GetCourseRecommendations", ReplyAction="*")]
        TrainingCompany.Web.ChatbotService.GetCourseRecommendationsResponse GetCourseRecommendations(TrainingCompany.Web.ChatbotService.GetCourseRecommendationsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://trainingcompany.com/GetCourseRecommendations", ReplyAction="*")]
        System.Threading.Tasks.Task<TrainingCompany.Web.ChatbotService.GetCourseRecommendationsResponse> GetCourseRecommendationsAsync(TrainingCompany.Web.ChatbotService.GetCourseRecommendationsRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ProcessMessageRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ProcessMessage", Namespace="http://trainingcompany.com/", Order=0)]
        public TrainingCompany.Web.ChatbotService.ProcessMessageRequestBody Body;
        
        public ProcessMessageRequest() {
        }
        
        public ProcessMessageRequest(TrainingCompany.Web.ChatbotService.ProcessMessageRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://trainingcompany.com/")]
    public partial class ProcessMessageRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string userMessage;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int userId;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string sessionId;
        
        public ProcessMessageRequestBody() {
        }
        
        public ProcessMessageRequestBody(string userMessage, int userId, string sessionId) {
            this.userMessage = userMessage;
            this.userId = userId;
            this.sessionId = sessionId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ProcessMessageResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ProcessMessageResponse", Namespace="http://trainingcompany.com/", Order=0)]
        public TrainingCompany.Web.ChatbotService.ProcessMessageResponseBody Body;
        
        public ProcessMessageResponse() {
        }
        
        public ProcessMessageResponse(TrainingCompany.Web.ChatbotService.ProcessMessageResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://trainingcompany.com/")]
    public partial class ProcessMessageResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public TrainingCompany.Web.ChatbotService.ChatResponse ProcessMessageResult;
        
        public ProcessMessageResponseBody() {
        }
        
        public ProcessMessageResponseBody(TrainingCompany.Web.ChatbotService.ChatResponse ProcessMessageResult) {
            this.ProcessMessageResult = ProcessMessageResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetQuickRepliesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetQuickReplies", Namespace="http://trainingcompany.com/", Order=0)]
        public TrainingCompany.Web.ChatbotService.GetQuickRepliesRequestBody Body;
        
        public GetQuickRepliesRequest() {
        }
        
        public GetQuickRepliesRequest(TrainingCompany.Web.ChatbotService.GetQuickRepliesRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetQuickRepliesRequestBody {
        
        public GetQuickRepliesRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetQuickRepliesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetQuickRepliesResponse", Namespace="http://trainingcompany.com/", Order=0)]
        public TrainingCompany.Web.ChatbotService.GetQuickRepliesResponseBody Body;
        
        public GetQuickRepliesResponse() {
        }
        
        public GetQuickRepliesResponse(TrainingCompany.Web.ChatbotService.GetQuickRepliesResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://trainingcompany.com/")]
    public partial class GetQuickRepliesResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public TrainingCompany.Web.ChatbotService.ArrayOfString GetQuickRepliesResult;
        
        public GetQuickRepliesResponseBody() {
        }
        
        public GetQuickRepliesResponseBody(TrainingCompany.Web.ChatbotService.ArrayOfString GetQuickRepliesResult) {
            this.GetQuickRepliesResult = GetQuickRepliesResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetCourseRecommendationsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetCourseRecommendations", Namespace="http://trainingcompany.com/", Order=0)]
        public TrainingCompany.Web.ChatbotService.GetCourseRecommendationsRequestBody Body;
        
        public GetCourseRecommendationsRequest() {
        }
        
        public GetCourseRecommendationsRequest(TrainingCompany.Web.ChatbotService.GetCourseRecommendationsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://trainingcompany.com/")]
    public partial class GetCourseRecommendationsRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int userId;
        
        public GetCourseRecommendationsRequestBody() {
        }
        
        public GetCourseRecommendationsRequestBody(int userId) {
            this.userId = userId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetCourseRecommendationsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetCourseRecommendationsResponse", Namespace="http://trainingcompany.com/", Order=0)]
        public TrainingCompany.Web.ChatbotService.GetCourseRecommendationsResponseBody Body;
        
        public GetCourseRecommendationsResponse() {
        }
        
        public GetCourseRecommendationsResponse(TrainingCompany.Web.ChatbotService.GetCourseRecommendationsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://trainingcompany.com/")]
    public partial class GetCourseRecommendationsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public TrainingCompany.Web.ChatbotService.CourseRecommendation[] GetCourseRecommendationsResult;
        
        public GetCourseRecommendationsResponseBody() {
        }
        
        public GetCourseRecommendationsResponseBody(TrainingCompany.Web.ChatbotService.CourseRecommendation[] GetCourseRecommendationsResult) {
            this.GetCourseRecommendationsResult = GetCourseRecommendationsResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ChatbotServiceSoapChannel : TrainingCompany.Web.ChatbotService.ChatbotServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ChatbotServiceSoapClient : System.ServiceModel.ClientBase<TrainingCompany.Web.ChatbotService.ChatbotServiceSoap>, TrainingCompany.Web.ChatbotService.ChatbotServiceSoap {
        
        public ChatbotServiceSoapClient() {
        }
        
        public ChatbotServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ChatbotServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ChatbotServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ChatbotServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TrainingCompany.Web.ChatbotService.ProcessMessageResponse TrainingCompany.Web.ChatbotService.ChatbotServiceSoap.ProcessMessage(TrainingCompany.Web.ChatbotService.ProcessMessageRequest request) {
            return base.Channel.ProcessMessage(request);
        }
        
        public TrainingCompany.Web.ChatbotService.ChatResponse ProcessMessage(string userMessage, int userId, string sessionId) {
            TrainingCompany.Web.ChatbotService.ProcessMessageRequest inValue = new TrainingCompany.Web.ChatbotService.ProcessMessageRequest();
            inValue.Body = new TrainingCompany.Web.ChatbotService.ProcessMessageRequestBody();
            inValue.Body.userMessage = userMessage;
            inValue.Body.userId = userId;
            inValue.Body.sessionId = sessionId;
            TrainingCompany.Web.ChatbotService.ProcessMessageResponse retVal = ((TrainingCompany.Web.ChatbotService.ChatbotServiceSoap)(this)).ProcessMessage(inValue);
            return retVal.Body.ProcessMessageResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TrainingCompany.Web.ChatbotService.ProcessMessageResponse> TrainingCompany.Web.ChatbotService.ChatbotServiceSoap.ProcessMessageAsync(TrainingCompany.Web.ChatbotService.ProcessMessageRequest request) {
            return base.Channel.ProcessMessageAsync(request);
        }
        
        public System.Threading.Tasks.Task<TrainingCompany.Web.ChatbotService.ProcessMessageResponse> ProcessMessageAsync(string userMessage, int userId, string sessionId) {
            TrainingCompany.Web.ChatbotService.ProcessMessageRequest inValue = new TrainingCompany.Web.ChatbotService.ProcessMessageRequest();
            inValue.Body = new TrainingCompany.Web.ChatbotService.ProcessMessageRequestBody();
            inValue.Body.userMessage = userMessage;
            inValue.Body.userId = userId;
            inValue.Body.sessionId = sessionId;
            return ((TrainingCompany.Web.ChatbotService.ChatbotServiceSoap)(this)).ProcessMessageAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TrainingCompany.Web.ChatbotService.GetQuickRepliesResponse TrainingCompany.Web.ChatbotService.ChatbotServiceSoap.GetQuickReplies(TrainingCompany.Web.ChatbotService.GetQuickRepliesRequest request) {
            return base.Channel.GetQuickReplies(request);
        }
        
        public TrainingCompany.Web.ChatbotService.ArrayOfString GetQuickReplies() {
            TrainingCompany.Web.ChatbotService.GetQuickRepliesRequest inValue = new TrainingCompany.Web.ChatbotService.GetQuickRepliesRequest();
            inValue.Body = new TrainingCompany.Web.ChatbotService.GetQuickRepliesRequestBody();
            TrainingCompany.Web.ChatbotService.GetQuickRepliesResponse retVal = ((TrainingCompany.Web.ChatbotService.ChatbotServiceSoap)(this)).GetQuickReplies(inValue);
            return retVal.Body.GetQuickRepliesResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TrainingCompany.Web.ChatbotService.GetQuickRepliesResponse> TrainingCompany.Web.ChatbotService.ChatbotServiceSoap.GetQuickRepliesAsync(TrainingCompany.Web.ChatbotService.GetQuickRepliesRequest request) {
            return base.Channel.GetQuickRepliesAsync(request);
        }
        
        public System.Threading.Tasks.Task<TrainingCompany.Web.ChatbotService.GetQuickRepliesResponse> GetQuickRepliesAsync() {
            TrainingCompany.Web.ChatbotService.GetQuickRepliesRequest inValue = new TrainingCompany.Web.ChatbotService.GetQuickRepliesRequest();
            inValue.Body = new TrainingCompany.Web.ChatbotService.GetQuickRepliesRequestBody();
            return ((TrainingCompany.Web.ChatbotService.ChatbotServiceSoap)(this)).GetQuickRepliesAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TrainingCompany.Web.ChatbotService.GetCourseRecommendationsResponse TrainingCompany.Web.ChatbotService.ChatbotServiceSoap.GetCourseRecommendations(TrainingCompany.Web.ChatbotService.GetCourseRecommendationsRequest request) {
            return base.Channel.GetCourseRecommendations(request);
        }
        
        public TrainingCompany.Web.ChatbotService.CourseRecommendation[] GetCourseRecommendations(int userId) {
            TrainingCompany.Web.ChatbotService.GetCourseRecommendationsRequest inValue = new TrainingCompany.Web.ChatbotService.GetCourseRecommendationsRequest();
            inValue.Body = new TrainingCompany.Web.ChatbotService.GetCourseRecommendationsRequestBody();
            inValue.Body.userId = userId;
            TrainingCompany.Web.ChatbotService.GetCourseRecommendationsResponse retVal = ((TrainingCompany.Web.ChatbotService.ChatbotServiceSoap)(this)).GetCourseRecommendations(inValue);
            return retVal.Body.GetCourseRecommendationsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TrainingCompany.Web.ChatbotService.GetCourseRecommendationsResponse> TrainingCompany.Web.ChatbotService.ChatbotServiceSoap.GetCourseRecommendationsAsync(TrainingCompany.Web.ChatbotService.GetCourseRecommendationsRequest request) {
            return base.Channel.GetCourseRecommendationsAsync(request);
        }
        
        public System.Threading.Tasks.Task<TrainingCompany.Web.ChatbotService.GetCourseRecommendationsResponse> GetCourseRecommendationsAsync(int userId) {
            TrainingCompany.Web.ChatbotService.GetCourseRecommendationsRequest inValue = new TrainingCompany.Web.ChatbotService.GetCourseRecommendationsRequest();
            inValue.Body = new TrainingCompany.Web.ChatbotService.GetCourseRecommendationsRequestBody();
            inValue.Body.userId = userId;
            return ((TrainingCompany.Web.ChatbotService.ChatbotServiceSoap)(this)).GetCourseRecommendationsAsync(inValue);
        }
    }
}
