//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrainingCompany.Web.UserService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UserRegistration", Namespace="http://trainingcompany.com/")]
    [System.SerializableAttribute()]
    public partial class UserRegistration : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PhoneField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PasswordField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Phone {
            get {
                return this.PhoneField;
            }
            set {
                if ((object.ReferenceEquals(this.PhoneField, value) != true)) {
                    this.PhoneField = value;
                    this.RaisePropertyChanged("Phone");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string Password {
            get {
                return this.PasswordField;
            }
            set {
                if ((object.ReferenceEquals(this.PasswordField, value) != true)) {
                    this.PasswordField = value;
                    this.RaisePropertyChanged("Password");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UserResponse", Namespace="http://trainingcompany.com/")]
    [System.SerializableAttribute()]
    public partial class UserResponse : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private bool SuccessField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private TrainingCompany.Web.UserService.User UserField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public bool Success {
            get {
                return this.SuccessField;
            }
            set {
                if ((this.SuccessField.Equals(value) != true)) {
                    this.SuccessField = value;
                    this.RaisePropertyChanged("Success");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Message {
            get {
                return this.MessageField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageField, value) != true)) {
                    this.MessageField = value;
                    this.RaisePropertyChanged("Message");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public TrainingCompany.Web.UserService.User User {
            get {
                return this.UserField;
            }
            set {
                if ((object.ReferenceEquals(this.UserField, value) != true)) {
                    this.UserField = value;
                    this.RaisePropertyChanged("User");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="User", Namespace="http://trainingcompany.com/")]
    [System.SerializableAttribute()]
    public partial class User : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int UserIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PhoneField;
        
        private bool IsAdminField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int UserID {
            get {
                return this.UserIDField;
            }
            set {
                if ((this.UserIDField.Equals(value) != true)) {
                    this.UserIDField = value;
                    this.RaisePropertyChanged("UserID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string Phone {
            get {
                return this.PhoneField;
            }
            set {
                if ((object.ReferenceEquals(this.PhoneField, value) != true)) {
                    this.PhoneField = value;
                    this.RaisePropertyChanged("Phone");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public bool IsAdmin {
            get {
                return this.IsAdminField;
            }
            set {
                if ((this.IsAdminField.Equals(value) != true)) {
                    this.IsAdminField = value;
                    this.RaisePropertyChanged("IsAdmin");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CourseItem", Namespace="http://trainingcompany.com/")]
    [System.SerializableAttribute()]
    public partial class CourseItem : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int CourseIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TitleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CategoryNameField;
        
        private decimal PriceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ScheduleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ModeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DurationField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int CourseID {
            get {
                return this.CourseIDField;
            }
            set {
                if ((this.CourseIDField.Equals(value) != true)) {
                    this.CourseIDField = value;
                    this.RaisePropertyChanged("CourseID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Title {
            get {
                return this.TitleField;
            }
            set {
                if ((object.ReferenceEquals(this.TitleField, value) != true)) {
                    this.TitleField = value;
                    this.RaisePropertyChanged("Title");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string CategoryName {
            get {
                return this.CategoryNameField;
            }
            set {
                if ((object.ReferenceEquals(this.CategoryNameField, value) != true)) {
                    this.CategoryNameField = value;
                    this.RaisePropertyChanged("CategoryName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public decimal Price {
            get {
                return this.PriceField;
            }
            set {
                if ((this.PriceField.Equals(value) != true)) {
                    this.PriceField = value;
                    this.RaisePropertyChanged("Price");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string Schedule {
            get {
                return this.ScheduleField;
            }
            set {
                if ((object.ReferenceEquals(this.ScheduleField, value) != true)) {
                    this.ScheduleField = value;
                    this.RaisePropertyChanged("Schedule");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string Mode {
            get {
                return this.ModeField;
            }
            set {
                if ((object.ReferenceEquals(this.ModeField, value) != true)) {
                    this.ModeField = value;
                    this.RaisePropertyChanged("Mode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string Duration {
            get {
                return this.DurationField;
            }
            set {
                if ((object.ReferenceEquals(this.DurationField, value) != true)) {
                    this.DurationField = value;
                    this.RaisePropertyChanged("Duration");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ServiceResponse", Namespace="http://trainingcompany.com/")]
    [System.SerializableAttribute()]
    public partial class ServiceResponse : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private bool SuccessField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DataField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public bool Success {
            get {
                return this.SuccessField;
            }
            set {
                if ((this.SuccessField.Equals(value) != true)) {
                    this.SuccessField = value;
                    this.RaisePropertyChanged("Success");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Message {
            get {
                return this.MessageField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageField, value) != true)) {
                    this.MessageField = value;
                    this.RaisePropertyChanged("Message");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Data {
            get {
                return this.DataField;
            }
            set {
                if ((object.ReferenceEquals(this.DataField, value) != true)) {
                    this.DataField = value;
                    this.RaisePropertyChanged("Data");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CartItem", Namespace="http://trainingcompany.com/")]
    [System.SerializableAttribute()]
    public partial class CartItem : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int CartIDField;
        
        private int CourseIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TitleField;
        
        private decimal PriceField;
        
        private int QuantityField;
        
        private decimal SubtotalField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int CartID {
            get {
                return this.CartIDField;
            }
            set {
                if ((this.CartIDField.Equals(value) != true)) {
                    this.CartIDField = value;
                    this.RaisePropertyChanged("CartID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int CourseID {
            get {
                return this.CourseIDField;
            }
            set {
                if ((this.CourseIDField.Equals(value) != true)) {
                    this.CourseIDField = value;
                    this.RaisePropertyChanged("CourseID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Title {
            get {
                return this.TitleField;
            }
            set {
                if ((object.ReferenceEquals(this.TitleField, value) != true)) {
                    this.TitleField = value;
                    this.RaisePropertyChanged("Title");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public decimal Price {
            get {
                return this.PriceField;
            }
            set {
                if ((this.PriceField.Equals(value) != true)) {
                    this.PriceField = value;
                    this.RaisePropertyChanged("Price");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public int Quantity {
            get {
                return this.QuantityField;
            }
            set {
                if ((this.QuantityField.Equals(value) != true)) {
                    this.QuantityField = value;
                    this.RaisePropertyChanged("Quantity");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=5)]
        public decimal Subtotal {
            get {
                return this.SubtotalField;
            }
            set {
                if ((this.SubtotalField.Equals(value) != true)) {
                    this.SubtotalField = value;
                    this.RaisePropertyChanged("Subtotal");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Notification", Namespace="http://trainingcompany.com/")]
    [System.SerializableAttribute()]
    public partial class Notification : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int NotificationIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TitleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TypeField;
        
        private bool IsReadField;
        
        private System.DateTime CreatedDateField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int NotificationID {
            get {
                return this.NotificationIDField;
            }
            set {
                if ((this.NotificationIDField.Equals(value) != true)) {
                    this.NotificationIDField = value;
                    this.RaisePropertyChanged("NotificationID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Title {
            get {
                return this.TitleField;
            }
            set {
                if ((object.ReferenceEquals(this.TitleField, value) != true)) {
                    this.TitleField = value;
                    this.RaisePropertyChanged("Title");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Message {
            get {
                return this.MessageField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageField, value) != true)) {
                    this.MessageField = value;
                    this.RaisePropertyChanged("Message");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string Type {
            get {
                return this.TypeField;
            }
            set {
                if ((object.ReferenceEquals(this.TypeField, value) != true)) {
                    this.TypeField = value;
                    this.RaisePropertyChanged("Type");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public bool IsRead {
            get {
                return this.IsReadField;
            }
            set {
                if ((this.IsReadField.Equals(value) != true)) {
                    this.IsReadField = value;
                    this.RaisePropertyChanged("IsRead");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=5)]
        public System.DateTime CreatedDate {
            get {
                return this.CreatedDateField;
            }
            set {
                if ((this.CreatedDateField.Equals(value) != true)) {
                    this.CreatedDateField = value;
                    this.RaisePropertyChanged("CreatedDate");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://trainingcompany.com/", ConfigurationName="UserService.UserServiceSoap")]
    public interface UserServiceSoap {
        
        // CODEGEN: Generating message contract since element name user from namespace http://trainingcompany.com/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://trainingcompany.com/Register", ReplyAction="*")]
        TrainingCompany.Web.UserService.RegisterResponse Register(TrainingCompany.Web.UserService.RegisterRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://trainingcompany.com/Register", ReplyAction="*")]
        System.Threading.Tasks.Task<TrainingCompany.Web.UserService.RegisterResponse> RegisterAsync(TrainingCompany.Web.UserService.RegisterRequest request);
        
        // CODEGEN: Generating message contract since element name email from namespace http://trainingcompany.com/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://trainingcompany.com/Login", ReplyAction="*")]
        TrainingCompany.Web.UserService.LoginResponse Login(TrainingCompany.Web.UserService.LoginRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://trainingcompany.com/Login", ReplyAction="*")]
        System.Threading.Tasks.Task<TrainingCompany.Web.UserService.LoginResponse> LoginAsync(TrainingCompany.Web.UserService.LoginRequest request);
        
        // CODEGEN: Generating message contract since element name keyword from namespace http://trainingcompany.com/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://trainingcompany.com/SearchCourses", ReplyAction="*")]
        TrainingCompany.Web.UserService.SearchCoursesResponse SearchCourses(TrainingCompany.Web.UserService.SearchCoursesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://trainingcompany.com/SearchCourses", ReplyAction="*")]
        System.Threading.Tasks.Task<TrainingCompany.Web.UserService.SearchCoursesResponse> SearchCoursesAsync(TrainingCompany.Web.UserService.SearchCoursesRequest request);
        
        // CODEGEN: Generating message contract since element name GetCourseDetailsResult from namespace http://trainingcompany.com/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://trainingcompany.com/GetCourseDetails", ReplyAction="*")]
        TrainingCompany.Web.UserService.GetCourseDetailsResponse GetCourseDetails(TrainingCompany.Web.UserService.GetCourseDetailsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://trainingcompany.com/GetCourseDetails", ReplyAction="*")]
        System.Threading.Tasks.Task<TrainingCompany.Web.UserService.GetCourseDetailsResponse> GetCourseDetailsAsync(TrainingCompany.Web.UserService.GetCourseDetailsRequest request);
        
        // CODEGEN: Generating message contract since element name AddToCartResult from namespace http://trainingcompany.com/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://trainingcompany.com/AddToCart", ReplyAction="*")]
        TrainingCompany.Web.UserService.AddToCartResponse AddToCart(TrainingCompany.Web.UserService.AddToCartRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://trainingcompany.com/AddToCart", ReplyAction="*")]
        System.Threading.Tasks.Task<TrainingCompany.Web.UserService.AddToCartResponse> AddToCartAsync(TrainingCompany.Web.UserService.AddToCartRequest request);
        
        // CODEGEN: Generating message contract since element name GetUserCartResult from namespace http://trainingcompany.com/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://trainingcompany.com/GetUserCart", ReplyAction="*")]
        TrainingCompany.Web.UserService.GetUserCartResponse GetUserCart(TrainingCompany.Web.UserService.GetUserCartRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://trainingcompany.com/GetUserCart", ReplyAction="*")]
        System.Threading.Tasks.Task<TrainingCompany.Web.UserService.GetUserCartResponse> GetUserCartAsync(TrainingCompany.Web.UserService.GetUserCartRequest request);
        
        // CODEGEN: Generating message contract since element name UpdateCartItemResult from namespace http://trainingcompany.com/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://trainingcompany.com/UpdateCartItem", ReplyAction="*")]
        TrainingCompany.Web.UserService.UpdateCartItemResponse UpdateCartItem(TrainingCompany.Web.UserService.UpdateCartItemRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://trainingcompany.com/UpdateCartItem", ReplyAction="*")]
        System.Threading.Tasks.Task<TrainingCompany.Web.UserService.UpdateCartItemResponse> UpdateCartItemAsync(TrainingCompany.Web.UserService.UpdateCartItemRequest request);
        
        // CODEGEN: Generating message contract since element name RemoveFromCartResult from namespace http://trainingcompany.com/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://trainingcompany.com/RemoveFromCart", ReplyAction="*")]
        TrainingCompany.Web.UserService.RemoveFromCartResponse RemoveFromCart(TrainingCompany.Web.UserService.RemoveFromCartRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://trainingcompany.com/RemoveFromCart", ReplyAction="*")]
        System.Threading.Tasks.Task<TrainingCompany.Web.UserService.RemoveFromCartResponse> RemoveFromCartAsync(TrainingCompany.Web.UserService.RemoveFromCartRequest request);
        
        // CODEGEN: Generating message contract since element name EnrollCourseResult from namespace http://trainingcompany.com/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://trainingcompany.com/EnrollCourse", ReplyAction="*")]
        TrainingCompany.Web.UserService.EnrollCourseResponse EnrollCourse(TrainingCompany.Web.UserService.EnrollCourseRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://trainingcompany.com/EnrollCourse", ReplyAction="*")]
        System.Threading.Tasks.Task<TrainingCompany.Web.UserService.EnrollCourseResponse> EnrollCourseAsync(TrainingCompany.Web.UserService.EnrollCourseRequest request);
        
        // CODEGEN: Generating message contract since element name GetUserNotificationsResult from namespace http://trainingcompany.com/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://trainingcompany.com/GetUserNotifications", ReplyAction="*")]
        TrainingCompany.Web.UserService.GetUserNotificationsResponse GetUserNotifications(TrainingCompany.Web.UserService.GetUserNotificationsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://trainingcompany.com/GetUserNotifications", ReplyAction="*")]
        System.Threading.Tasks.Task<TrainingCompany.Web.UserService.GetUserNotificationsResponse> GetUserNotificationsAsync(TrainingCompany.Web.UserService.GetUserNotificationsRequest request);
        
        // CODEGEN: Generating message contract since element name MarkNotificationAsReadResult from namespace http://trainingcompany.com/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://trainingcompany.com/MarkNotificationAsRead", ReplyAction="*")]
        TrainingCompany.Web.UserService.MarkNotificationAsReadResponse MarkNotificationAsRead(TrainingCompany.Web.UserService.MarkNotificationAsReadRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://trainingcompany.com/MarkNotificationAsRead", ReplyAction="*")]
        System.Threading.Tasks.Task<TrainingCompany.Web.UserService.MarkNotificationAsReadResponse> MarkNotificationAsReadAsync(TrainingCompany.Web.UserService.MarkNotificationAsReadRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RegisterRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Register", Namespace="http://trainingcompany.com/", Order=0)]
        public TrainingCompany.Web.UserService.RegisterRequestBody Body;
        
        public RegisterRequest() {
        }
        
        public RegisterRequest(TrainingCompany.Web.UserService.RegisterRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://trainingcompany.com/")]
    public partial class RegisterRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public TrainingCompany.Web.UserService.UserRegistration user;
        
        public RegisterRequestBody() {
        }
        
        public RegisterRequestBody(TrainingCompany.Web.UserService.UserRegistration user) {
            this.user = user;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RegisterResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="RegisterResponse", Namespace="http://trainingcompany.com/", Order=0)]
        public TrainingCompany.Web.UserService.RegisterResponseBody Body;
        
        public RegisterResponse() {
        }
        
        public RegisterResponse(TrainingCompany.Web.UserService.RegisterResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://trainingcompany.com/")]
    public partial class RegisterResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public TrainingCompany.Web.UserService.UserResponse RegisterResult;
        
        public RegisterResponseBody() {
        }
        
        public RegisterResponseBody(TrainingCompany.Web.UserService.UserResponse RegisterResult) {
            this.RegisterResult = RegisterResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class LoginRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Login", Namespace="http://trainingcompany.com/", Order=0)]
        public TrainingCompany.Web.UserService.LoginRequestBody Body;
        
        public LoginRequest() {
        }
        
        public LoginRequest(TrainingCompany.Web.UserService.LoginRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://trainingcompany.com/")]
    public partial class LoginRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string email;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string password;
        
        public LoginRequestBody() {
        }
        
        public LoginRequestBody(string email, string password) {
            this.email = email;
            this.password = password;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class LoginResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="LoginResponse", Namespace="http://trainingcompany.com/", Order=0)]
        public TrainingCompany.Web.UserService.LoginResponseBody Body;
        
        public LoginResponse() {
        }
        
        public LoginResponse(TrainingCompany.Web.UserService.LoginResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://trainingcompany.com/")]
    public partial class LoginResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public TrainingCompany.Web.UserService.UserResponse LoginResult;
        
        public LoginResponseBody() {
        }
        
        public LoginResponseBody(TrainingCompany.Web.UserService.UserResponse LoginResult) {
            this.LoginResult = LoginResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SearchCoursesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SearchCourses", Namespace="http://trainingcompany.com/", Order=0)]
        public TrainingCompany.Web.UserService.SearchCoursesRequestBody Body;
        
        public SearchCoursesRequest() {
        }
        
        public SearchCoursesRequest(TrainingCompany.Web.UserService.SearchCoursesRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://trainingcompany.com/")]
    public partial class SearchCoursesRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string keyword;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int categoryId;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string mode;
        
        public SearchCoursesRequestBody() {
        }
        
        public SearchCoursesRequestBody(string keyword, int categoryId, string mode) {
            this.keyword = keyword;
            this.categoryId = categoryId;
            this.mode = mode;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SearchCoursesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SearchCoursesResponse", Namespace="http://trainingcompany.com/", Order=0)]
        public TrainingCompany.Web.UserService.SearchCoursesResponseBody Body;
        
        public SearchCoursesResponse() {
        }
        
        public SearchCoursesResponse(TrainingCompany.Web.UserService.SearchCoursesResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://trainingcompany.com/")]
    public partial class SearchCoursesResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public TrainingCompany.Web.UserService.CourseItem[] SearchCoursesResult;
        
        public SearchCoursesResponseBody() {
        }
        
        public SearchCoursesResponseBody(TrainingCompany.Web.UserService.CourseItem[] SearchCoursesResult) {
            this.SearchCoursesResult = SearchCoursesResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetCourseDetailsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetCourseDetails", Namespace="http://trainingcompany.com/", Order=0)]
        public TrainingCompany.Web.UserService.GetCourseDetailsRequestBody Body;
        
        public GetCourseDetailsRequest() {
        }
        
        public GetCourseDetailsRequest(TrainingCompany.Web.UserService.GetCourseDetailsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://trainingcompany.com/")]
    public partial class GetCourseDetailsRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int courseId;
        
        public GetCourseDetailsRequestBody() {
        }
        
        public GetCourseDetailsRequestBody(int courseId) {
            this.courseId = courseId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetCourseDetailsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetCourseDetailsResponse", Namespace="http://trainingcompany.com/", Order=0)]
        public TrainingCompany.Web.UserService.GetCourseDetailsResponseBody Body;
        
        public GetCourseDetailsResponse() {
        }
        
        public GetCourseDetailsResponse(TrainingCompany.Web.UserService.GetCourseDetailsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://trainingcompany.com/")]
    public partial class GetCourseDetailsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public TrainingCompany.Web.UserService.CourseItem GetCourseDetailsResult;
        
        public GetCourseDetailsResponseBody() {
        }
        
        public GetCourseDetailsResponseBody(TrainingCompany.Web.UserService.CourseItem GetCourseDetailsResult) {
            this.GetCourseDetailsResult = GetCourseDetailsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddToCartRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddToCart", Namespace="http://trainingcompany.com/", Order=0)]
        public TrainingCompany.Web.UserService.AddToCartRequestBody Body;
        
        public AddToCartRequest() {
        }
        
        public AddToCartRequest(TrainingCompany.Web.UserService.AddToCartRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://trainingcompany.com/")]
    public partial class AddToCartRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int userId;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int courseId;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public int quantity;
        
        public AddToCartRequestBody() {
        }
        
        public AddToCartRequestBody(int userId, int courseId, int quantity) {
            this.userId = userId;
            this.courseId = courseId;
            this.quantity = quantity;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddToCartResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddToCartResponse", Namespace="http://trainingcompany.com/", Order=0)]
        public TrainingCompany.Web.UserService.AddToCartResponseBody Body;
        
        public AddToCartResponse() {
        }
        
        public AddToCartResponse(TrainingCompany.Web.UserService.AddToCartResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://trainingcompany.com/")]
    public partial class AddToCartResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public TrainingCompany.Web.UserService.ServiceResponse AddToCartResult;
        
        public AddToCartResponseBody() {
        }
        
        public AddToCartResponseBody(TrainingCompany.Web.UserService.ServiceResponse AddToCartResult) {
            this.AddToCartResult = AddToCartResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetUserCartRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetUserCart", Namespace="http://trainingcompany.com/", Order=0)]
        public TrainingCompany.Web.UserService.GetUserCartRequestBody Body;
        
        public GetUserCartRequest() {
        }
        
        public GetUserCartRequest(TrainingCompany.Web.UserService.GetUserCartRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://trainingcompany.com/")]
    public partial class GetUserCartRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int userId;
        
        public GetUserCartRequestBody() {
        }
        
        public GetUserCartRequestBody(int userId) {
            this.userId = userId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetUserCartResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetUserCartResponse", Namespace="http://trainingcompany.com/", Order=0)]
        public TrainingCompany.Web.UserService.GetUserCartResponseBody Body;
        
        public GetUserCartResponse() {
        }
        
        public GetUserCartResponse(TrainingCompany.Web.UserService.GetUserCartResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://trainingcompany.com/")]
    public partial class GetUserCartResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public TrainingCompany.Web.UserService.CartItem[] GetUserCartResult;
        
        public GetUserCartResponseBody() {
        }
        
        public GetUserCartResponseBody(TrainingCompany.Web.UserService.CartItem[] GetUserCartResult) {
            this.GetUserCartResult = GetUserCartResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateCartItemRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateCartItem", Namespace="http://trainingcompany.com/", Order=0)]
        public TrainingCompany.Web.UserService.UpdateCartItemRequestBody Body;
        
        public UpdateCartItemRequest() {
        }
        
        public UpdateCartItemRequest(TrainingCompany.Web.UserService.UpdateCartItemRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://trainingcompany.com/")]
    public partial class UpdateCartItemRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int cartId;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int quantity;
        
        public UpdateCartItemRequestBody() {
        }
        
        public UpdateCartItemRequestBody(int cartId, int quantity) {
            this.cartId = cartId;
            this.quantity = quantity;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateCartItemResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateCartItemResponse", Namespace="http://trainingcompany.com/", Order=0)]
        public TrainingCompany.Web.UserService.UpdateCartItemResponseBody Body;
        
        public UpdateCartItemResponse() {
        }
        
        public UpdateCartItemResponse(TrainingCompany.Web.UserService.UpdateCartItemResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://trainingcompany.com/")]
    public partial class UpdateCartItemResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public TrainingCompany.Web.UserService.ServiceResponse UpdateCartItemResult;
        
        public UpdateCartItemResponseBody() {
        }
        
        public UpdateCartItemResponseBody(TrainingCompany.Web.UserService.ServiceResponse UpdateCartItemResult) {
            this.UpdateCartItemResult = UpdateCartItemResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RemoveFromCartRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="RemoveFromCart", Namespace="http://trainingcompany.com/", Order=0)]
        public TrainingCompany.Web.UserService.RemoveFromCartRequestBody Body;
        
        public RemoveFromCartRequest() {
        }
        
        public RemoveFromCartRequest(TrainingCompany.Web.UserService.RemoveFromCartRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://trainingcompany.com/")]
    public partial class RemoveFromCartRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int cartId;
        
        public RemoveFromCartRequestBody() {
        }
        
        public RemoveFromCartRequestBody(int cartId) {
            this.cartId = cartId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RemoveFromCartResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="RemoveFromCartResponse", Namespace="http://trainingcompany.com/", Order=0)]
        public TrainingCompany.Web.UserService.RemoveFromCartResponseBody Body;
        
        public RemoveFromCartResponse() {
        }
        
        public RemoveFromCartResponse(TrainingCompany.Web.UserService.RemoveFromCartResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://trainingcompany.com/")]
    public partial class RemoveFromCartResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public TrainingCompany.Web.UserService.ServiceResponse RemoveFromCartResult;
        
        public RemoveFromCartResponseBody() {
        }
        
        public RemoveFromCartResponseBody(TrainingCompany.Web.UserService.ServiceResponse RemoveFromCartResult) {
            this.RemoveFromCartResult = RemoveFromCartResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class EnrollCourseRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="EnrollCourse", Namespace="http://trainingcompany.com/", Order=0)]
        public TrainingCompany.Web.UserService.EnrollCourseRequestBody Body;
        
        public EnrollCourseRequest() {
        }
        
        public EnrollCourseRequest(TrainingCompany.Web.UserService.EnrollCourseRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://trainingcompany.com/")]
    public partial class EnrollCourseRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int userId;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int courseId;
        
        public EnrollCourseRequestBody() {
        }
        
        public EnrollCourseRequestBody(int userId, int courseId) {
            this.userId = userId;
            this.courseId = courseId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class EnrollCourseResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="EnrollCourseResponse", Namespace="http://trainingcompany.com/", Order=0)]
        public TrainingCompany.Web.UserService.EnrollCourseResponseBody Body;
        
        public EnrollCourseResponse() {
        }
        
        public EnrollCourseResponse(TrainingCompany.Web.UserService.EnrollCourseResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://trainingcompany.com/")]
    public partial class EnrollCourseResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public TrainingCompany.Web.UserService.ServiceResponse EnrollCourseResult;
        
        public EnrollCourseResponseBody() {
        }
        
        public EnrollCourseResponseBody(TrainingCompany.Web.UserService.ServiceResponse EnrollCourseResult) {
            this.EnrollCourseResult = EnrollCourseResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetUserNotificationsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetUserNotifications", Namespace="http://trainingcompany.com/", Order=0)]
        public TrainingCompany.Web.UserService.GetUserNotificationsRequestBody Body;
        
        public GetUserNotificationsRequest() {
        }
        
        public GetUserNotificationsRequest(TrainingCompany.Web.UserService.GetUserNotificationsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://trainingcompany.com/")]
    public partial class GetUserNotificationsRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int userId;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public bool unreadOnly;
        
        public GetUserNotificationsRequestBody() {
        }
        
        public GetUserNotificationsRequestBody(int userId, bool unreadOnly) {
            this.userId = userId;
            this.unreadOnly = unreadOnly;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetUserNotificationsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetUserNotificationsResponse", Namespace="http://trainingcompany.com/", Order=0)]
        public TrainingCompany.Web.UserService.GetUserNotificationsResponseBody Body;
        
        public GetUserNotificationsResponse() {
        }
        
        public GetUserNotificationsResponse(TrainingCompany.Web.UserService.GetUserNotificationsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://trainingcompany.com/")]
    public partial class GetUserNotificationsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public TrainingCompany.Web.UserService.Notification[] GetUserNotificationsResult;
        
        public GetUserNotificationsResponseBody() {
        }
        
        public GetUserNotificationsResponseBody(TrainingCompany.Web.UserService.Notification[] GetUserNotificationsResult) {
            this.GetUserNotificationsResult = GetUserNotificationsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class MarkNotificationAsReadRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="MarkNotificationAsRead", Namespace="http://trainingcompany.com/", Order=0)]
        public TrainingCompany.Web.UserService.MarkNotificationAsReadRequestBody Body;
        
        public MarkNotificationAsReadRequest() {
        }
        
        public MarkNotificationAsReadRequest(TrainingCompany.Web.UserService.MarkNotificationAsReadRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://trainingcompany.com/")]
    public partial class MarkNotificationAsReadRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int notificationId;
        
        public MarkNotificationAsReadRequestBody() {
        }
        
        public MarkNotificationAsReadRequestBody(int notificationId) {
            this.notificationId = notificationId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class MarkNotificationAsReadResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="MarkNotificationAsReadResponse", Namespace="http://trainingcompany.com/", Order=0)]
        public TrainingCompany.Web.UserService.MarkNotificationAsReadResponseBody Body;
        
        public MarkNotificationAsReadResponse() {
        }
        
        public MarkNotificationAsReadResponse(TrainingCompany.Web.UserService.MarkNotificationAsReadResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://trainingcompany.com/")]
    public partial class MarkNotificationAsReadResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public TrainingCompany.Web.UserService.ServiceResponse MarkNotificationAsReadResult;
        
        public MarkNotificationAsReadResponseBody() {
        }
        
        public MarkNotificationAsReadResponseBody(TrainingCompany.Web.UserService.ServiceResponse MarkNotificationAsReadResult) {
            this.MarkNotificationAsReadResult = MarkNotificationAsReadResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface UserServiceSoapChannel : TrainingCompany.Web.UserService.UserServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class UserServiceSoapClient : System.ServiceModel.ClientBase<TrainingCompany.Web.UserService.UserServiceSoap>, TrainingCompany.Web.UserService.UserServiceSoap {
        
        public UserServiceSoapClient() {
        }
        
        public UserServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public UserServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UserServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UserServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TrainingCompany.Web.UserService.RegisterResponse TrainingCompany.Web.UserService.UserServiceSoap.Register(TrainingCompany.Web.UserService.RegisterRequest request) {
            return base.Channel.Register(request);
        }
        
        public TrainingCompany.Web.UserService.UserResponse Register(TrainingCompany.Web.UserService.UserRegistration user) {
            TrainingCompany.Web.UserService.RegisterRequest inValue = new TrainingCompany.Web.UserService.RegisterRequest();
            inValue.Body = new TrainingCompany.Web.UserService.RegisterRequestBody();
            inValue.Body.user = user;
            TrainingCompany.Web.UserService.RegisterResponse retVal = ((TrainingCompany.Web.UserService.UserServiceSoap)(this)).Register(inValue);
            return retVal.Body.RegisterResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TrainingCompany.Web.UserService.RegisterResponse> TrainingCompany.Web.UserService.UserServiceSoap.RegisterAsync(TrainingCompany.Web.UserService.RegisterRequest request) {
            return base.Channel.RegisterAsync(request);
        }
        
        public System.Threading.Tasks.Task<TrainingCompany.Web.UserService.RegisterResponse> RegisterAsync(TrainingCompany.Web.UserService.UserRegistration user) {
            TrainingCompany.Web.UserService.RegisterRequest inValue = new TrainingCompany.Web.UserService.RegisterRequest();
            inValue.Body = new TrainingCompany.Web.UserService.RegisterRequestBody();
            inValue.Body.user = user;
            return ((TrainingCompany.Web.UserService.UserServiceSoap)(this)).RegisterAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TrainingCompany.Web.UserService.LoginResponse TrainingCompany.Web.UserService.UserServiceSoap.Login(TrainingCompany.Web.UserService.LoginRequest request) {
            return base.Channel.Login(request);
        }
        
        public TrainingCompany.Web.UserService.UserResponse Login(string email, string password) {
            TrainingCompany.Web.UserService.LoginRequest inValue = new TrainingCompany.Web.UserService.LoginRequest();
            inValue.Body = new TrainingCompany.Web.UserService.LoginRequestBody();
            inValue.Body.email = email;
            inValue.Body.password = password;
            TrainingCompany.Web.UserService.LoginResponse retVal = ((TrainingCompany.Web.UserService.UserServiceSoap)(this)).Login(inValue);
            return retVal.Body.LoginResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TrainingCompany.Web.UserService.LoginResponse> TrainingCompany.Web.UserService.UserServiceSoap.LoginAsync(TrainingCompany.Web.UserService.LoginRequest request) {
            return base.Channel.LoginAsync(request);
        }
        
        public System.Threading.Tasks.Task<TrainingCompany.Web.UserService.LoginResponse> LoginAsync(string email, string password) {
            TrainingCompany.Web.UserService.LoginRequest inValue = new TrainingCompany.Web.UserService.LoginRequest();
            inValue.Body = new TrainingCompany.Web.UserService.LoginRequestBody();
            inValue.Body.email = email;
            inValue.Body.password = password;
            return ((TrainingCompany.Web.UserService.UserServiceSoap)(this)).LoginAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TrainingCompany.Web.UserService.SearchCoursesResponse TrainingCompany.Web.UserService.UserServiceSoap.SearchCourses(TrainingCompany.Web.UserService.SearchCoursesRequest request) {
            return base.Channel.SearchCourses(request);
        }
        
        public TrainingCompany.Web.UserService.CourseItem[] SearchCourses(string keyword, int categoryId, string mode) {
            TrainingCompany.Web.UserService.SearchCoursesRequest inValue = new TrainingCompany.Web.UserService.SearchCoursesRequest();
            inValue.Body = new TrainingCompany.Web.UserService.SearchCoursesRequestBody();
            inValue.Body.keyword = keyword;
            inValue.Body.categoryId = categoryId;
            inValue.Body.mode = mode;
            TrainingCompany.Web.UserService.SearchCoursesResponse retVal = ((TrainingCompany.Web.UserService.UserServiceSoap)(this)).SearchCourses(inValue);
            return retVal.Body.SearchCoursesResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TrainingCompany.Web.UserService.SearchCoursesResponse> TrainingCompany.Web.UserService.UserServiceSoap.SearchCoursesAsync(TrainingCompany.Web.UserService.SearchCoursesRequest request) {
            return base.Channel.SearchCoursesAsync(request);
        }
        
        public System.Threading.Tasks.Task<TrainingCompany.Web.UserService.SearchCoursesResponse> SearchCoursesAsync(string keyword, int categoryId, string mode) {
            TrainingCompany.Web.UserService.SearchCoursesRequest inValue = new TrainingCompany.Web.UserService.SearchCoursesRequest();
            inValue.Body = new TrainingCompany.Web.UserService.SearchCoursesRequestBody();
            inValue.Body.keyword = keyword;
            inValue.Body.categoryId = categoryId;
            inValue.Body.mode = mode;
            return ((TrainingCompany.Web.UserService.UserServiceSoap)(this)).SearchCoursesAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TrainingCompany.Web.UserService.GetCourseDetailsResponse TrainingCompany.Web.UserService.UserServiceSoap.GetCourseDetails(TrainingCompany.Web.UserService.GetCourseDetailsRequest request) {
            return base.Channel.GetCourseDetails(request);
        }
        
        public TrainingCompany.Web.UserService.CourseItem GetCourseDetails(int courseId) {
            TrainingCompany.Web.UserService.GetCourseDetailsRequest inValue = new TrainingCompany.Web.UserService.GetCourseDetailsRequest();
            inValue.Body = new TrainingCompany.Web.UserService.GetCourseDetailsRequestBody();
            inValue.Body.courseId = courseId;
            TrainingCompany.Web.UserService.GetCourseDetailsResponse retVal = ((TrainingCompany.Web.UserService.UserServiceSoap)(this)).GetCourseDetails(inValue);
            return retVal.Body.GetCourseDetailsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TrainingCompany.Web.UserService.GetCourseDetailsResponse> TrainingCompany.Web.UserService.UserServiceSoap.GetCourseDetailsAsync(TrainingCompany.Web.UserService.GetCourseDetailsRequest request) {
            return base.Channel.GetCourseDetailsAsync(request);
        }
        
        public System.Threading.Tasks.Task<TrainingCompany.Web.UserService.GetCourseDetailsResponse> GetCourseDetailsAsync(int courseId) {
            TrainingCompany.Web.UserService.GetCourseDetailsRequest inValue = new TrainingCompany.Web.UserService.GetCourseDetailsRequest();
            inValue.Body = new TrainingCompany.Web.UserService.GetCourseDetailsRequestBody();
            inValue.Body.courseId = courseId;
            return ((TrainingCompany.Web.UserService.UserServiceSoap)(this)).GetCourseDetailsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TrainingCompany.Web.UserService.AddToCartResponse TrainingCompany.Web.UserService.UserServiceSoap.AddToCart(TrainingCompany.Web.UserService.AddToCartRequest request) {
            return base.Channel.AddToCart(request);
        }
        
        public TrainingCompany.Web.UserService.ServiceResponse AddToCart(int userId, int courseId, int quantity) {
            TrainingCompany.Web.UserService.AddToCartRequest inValue = new TrainingCompany.Web.UserService.AddToCartRequest();
            inValue.Body = new TrainingCompany.Web.UserService.AddToCartRequestBody();
            inValue.Body.userId = userId;
            inValue.Body.courseId = courseId;
            inValue.Body.quantity = quantity;
            TrainingCompany.Web.UserService.AddToCartResponse retVal = ((TrainingCompany.Web.UserService.UserServiceSoap)(this)).AddToCart(inValue);
            return retVal.Body.AddToCartResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TrainingCompany.Web.UserService.AddToCartResponse> TrainingCompany.Web.UserService.UserServiceSoap.AddToCartAsync(TrainingCompany.Web.UserService.AddToCartRequest request) {
            return base.Channel.AddToCartAsync(request);
        }
        
        public System.Threading.Tasks.Task<TrainingCompany.Web.UserService.AddToCartResponse> AddToCartAsync(int userId, int courseId, int quantity) {
            TrainingCompany.Web.UserService.AddToCartRequest inValue = new TrainingCompany.Web.UserService.AddToCartRequest();
            inValue.Body = new TrainingCompany.Web.UserService.AddToCartRequestBody();
            inValue.Body.userId = userId;
            inValue.Body.courseId = courseId;
            inValue.Body.quantity = quantity;
            return ((TrainingCompany.Web.UserService.UserServiceSoap)(this)).AddToCartAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TrainingCompany.Web.UserService.GetUserCartResponse TrainingCompany.Web.UserService.UserServiceSoap.GetUserCart(TrainingCompany.Web.UserService.GetUserCartRequest request) {
            return base.Channel.GetUserCart(request);
        }
        
        public TrainingCompany.Web.UserService.CartItem[] GetUserCart(int userId) {
            TrainingCompany.Web.UserService.GetUserCartRequest inValue = new TrainingCompany.Web.UserService.GetUserCartRequest();
            inValue.Body = new TrainingCompany.Web.UserService.GetUserCartRequestBody();
            inValue.Body.userId = userId;
            TrainingCompany.Web.UserService.GetUserCartResponse retVal = ((TrainingCompany.Web.UserService.UserServiceSoap)(this)).GetUserCart(inValue);
            return retVal.Body.GetUserCartResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TrainingCompany.Web.UserService.GetUserCartResponse> TrainingCompany.Web.UserService.UserServiceSoap.GetUserCartAsync(TrainingCompany.Web.UserService.GetUserCartRequest request) {
            return base.Channel.GetUserCartAsync(request);
        }
        
        public System.Threading.Tasks.Task<TrainingCompany.Web.UserService.GetUserCartResponse> GetUserCartAsync(int userId) {
            TrainingCompany.Web.UserService.GetUserCartRequest inValue = new TrainingCompany.Web.UserService.GetUserCartRequest();
            inValue.Body = new TrainingCompany.Web.UserService.GetUserCartRequestBody();
            inValue.Body.userId = userId;
            return ((TrainingCompany.Web.UserService.UserServiceSoap)(this)).GetUserCartAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TrainingCompany.Web.UserService.UpdateCartItemResponse TrainingCompany.Web.UserService.UserServiceSoap.UpdateCartItem(TrainingCompany.Web.UserService.UpdateCartItemRequest request) {
            return base.Channel.UpdateCartItem(request);
        }
        
        public TrainingCompany.Web.UserService.ServiceResponse UpdateCartItem(int cartId, int quantity) {
            TrainingCompany.Web.UserService.UpdateCartItemRequest inValue = new TrainingCompany.Web.UserService.UpdateCartItemRequest();
            inValue.Body = new TrainingCompany.Web.UserService.UpdateCartItemRequestBody();
            inValue.Body.cartId = cartId;
            inValue.Body.quantity = quantity;
            TrainingCompany.Web.UserService.UpdateCartItemResponse retVal = ((TrainingCompany.Web.UserService.UserServiceSoap)(this)).UpdateCartItem(inValue);
            return retVal.Body.UpdateCartItemResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TrainingCompany.Web.UserService.UpdateCartItemResponse> TrainingCompany.Web.UserService.UserServiceSoap.UpdateCartItemAsync(TrainingCompany.Web.UserService.UpdateCartItemRequest request) {
            return base.Channel.UpdateCartItemAsync(request);
        }
        
        public System.Threading.Tasks.Task<TrainingCompany.Web.UserService.UpdateCartItemResponse> UpdateCartItemAsync(int cartId, int quantity) {
            TrainingCompany.Web.UserService.UpdateCartItemRequest inValue = new TrainingCompany.Web.UserService.UpdateCartItemRequest();
            inValue.Body = new TrainingCompany.Web.UserService.UpdateCartItemRequestBody();
            inValue.Body.cartId = cartId;
            inValue.Body.quantity = quantity;
            return ((TrainingCompany.Web.UserService.UserServiceSoap)(this)).UpdateCartItemAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TrainingCompany.Web.UserService.RemoveFromCartResponse TrainingCompany.Web.UserService.UserServiceSoap.RemoveFromCart(TrainingCompany.Web.UserService.RemoveFromCartRequest request) {
            return base.Channel.RemoveFromCart(request);
        }
        
        public TrainingCompany.Web.UserService.ServiceResponse RemoveFromCart(int cartId) {
            TrainingCompany.Web.UserService.RemoveFromCartRequest inValue = new TrainingCompany.Web.UserService.RemoveFromCartRequest();
            inValue.Body = new TrainingCompany.Web.UserService.RemoveFromCartRequestBody();
            inValue.Body.cartId = cartId;
            TrainingCompany.Web.UserService.RemoveFromCartResponse retVal = ((TrainingCompany.Web.UserService.UserServiceSoap)(this)).RemoveFromCart(inValue);
            return retVal.Body.RemoveFromCartResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TrainingCompany.Web.UserService.RemoveFromCartResponse> TrainingCompany.Web.UserService.UserServiceSoap.RemoveFromCartAsync(TrainingCompany.Web.UserService.RemoveFromCartRequest request) {
            return base.Channel.RemoveFromCartAsync(request);
        }
        
        public System.Threading.Tasks.Task<TrainingCompany.Web.UserService.RemoveFromCartResponse> RemoveFromCartAsync(int cartId) {
            TrainingCompany.Web.UserService.RemoveFromCartRequest inValue = new TrainingCompany.Web.UserService.RemoveFromCartRequest();
            inValue.Body = new TrainingCompany.Web.UserService.RemoveFromCartRequestBody();
            inValue.Body.cartId = cartId;
            return ((TrainingCompany.Web.UserService.UserServiceSoap)(this)).RemoveFromCartAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TrainingCompany.Web.UserService.EnrollCourseResponse TrainingCompany.Web.UserService.UserServiceSoap.EnrollCourse(TrainingCompany.Web.UserService.EnrollCourseRequest request) {
            return base.Channel.EnrollCourse(request);
        }
        
        public TrainingCompany.Web.UserService.ServiceResponse EnrollCourse(int userId, int courseId) {
            TrainingCompany.Web.UserService.EnrollCourseRequest inValue = new TrainingCompany.Web.UserService.EnrollCourseRequest();
            inValue.Body = new TrainingCompany.Web.UserService.EnrollCourseRequestBody();
            inValue.Body.userId = userId;
            inValue.Body.courseId = courseId;
            TrainingCompany.Web.UserService.EnrollCourseResponse retVal = ((TrainingCompany.Web.UserService.UserServiceSoap)(this)).EnrollCourse(inValue);
            return retVal.Body.EnrollCourseResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TrainingCompany.Web.UserService.EnrollCourseResponse> TrainingCompany.Web.UserService.UserServiceSoap.EnrollCourseAsync(TrainingCompany.Web.UserService.EnrollCourseRequest request) {
            return base.Channel.EnrollCourseAsync(request);
        }
        
        public System.Threading.Tasks.Task<TrainingCompany.Web.UserService.EnrollCourseResponse> EnrollCourseAsync(int userId, int courseId) {
            TrainingCompany.Web.UserService.EnrollCourseRequest inValue = new TrainingCompany.Web.UserService.EnrollCourseRequest();
            inValue.Body = new TrainingCompany.Web.UserService.EnrollCourseRequestBody();
            inValue.Body.userId = userId;
            inValue.Body.courseId = courseId;
            return ((TrainingCompany.Web.UserService.UserServiceSoap)(this)).EnrollCourseAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TrainingCompany.Web.UserService.GetUserNotificationsResponse TrainingCompany.Web.UserService.UserServiceSoap.GetUserNotifications(TrainingCompany.Web.UserService.GetUserNotificationsRequest request) {
            return base.Channel.GetUserNotifications(request);
        }
        
        public TrainingCompany.Web.UserService.Notification[] GetUserNotifications(int userId, bool unreadOnly) {
            TrainingCompany.Web.UserService.GetUserNotificationsRequest inValue = new TrainingCompany.Web.UserService.GetUserNotificationsRequest();
            inValue.Body = new TrainingCompany.Web.UserService.GetUserNotificationsRequestBody();
            inValue.Body.userId = userId;
            inValue.Body.unreadOnly = unreadOnly;
            TrainingCompany.Web.UserService.GetUserNotificationsResponse retVal = ((TrainingCompany.Web.UserService.UserServiceSoap)(this)).GetUserNotifications(inValue);
            return retVal.Body.GetUserNotificationsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TrainingCompany.Web.UserService.GetUserNotificationsResponse> TrainingCompany.Web.UserService.UserServiceSoap.GetUserNotificationsAsync(TrainingCompany.Web.UserService.GetUserNotificationsRequest request) {
            return base.Channel.GetUserNotificationsAsync(request);
        }
        
        public System.Threading.Tasks.Task<TrainingCompany.Web.UserService.GetUserNotificationsResponse> GetUserNotificationsAsync(int userId, bool unreadOnly) {
            TrainingCompany.Web.UserService.GetUserNotificationsRequest inValue = new TrainingCompany.Web.UserService.GetUserNotificationsRequest();
            inValue.Body = new TrainingCompany.Web.UserService.GetUserNotificationsRequestBody();
            inValue.Body.userId = userId;
            inValue.Body.unreadOnly = unreadOnly;
            return ((TrainingCompany.Web.UserService.UserServiceSoap)(this)).GetUserNotificationsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TrainingCompany.Web.UserService.MarkNotificationAsReadResponse TrainingCompany.Web.UserService.UserServiceSoap.MarkNotificationAsRead(TrainingCompany.Web.UserService.MarkNotificationAsReadRequest request) {
            return base.Channel.MarkNotificationAsRead(request);
        }
        
        public TrainingCompany.Web.UserService.ServiceResponse MarkNotificationAsRead(int notificationId) {
            TrainingCompany.Web.UserService.MarkNotificationAsReadRequest inValue = new TrainingCompany.Web.UserService.MarkNotificationAsReadRequest();
            inValue.Body = new TrainingCompany.Web.UserService.MarkNotificationAsReadRequestBody();
            inValue.Body.notificationId = notificationId;
            TrainingCompany.Web.UserService.MarkNotificationAsReadResponse retVal = ((TrainingCompany.Web.UserService.UserServiceSoap)(this)).MarkNotificationAsRead(inValue);
            return retVal.Body.MarkNotificationAsReadResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TrainingCompany.Web.UserService.MarkNotificationAsReadResponse> TrainingCompany.Web.UserService.UserServiceSoap.MarkNotificationAsReadAsync(TrainingCompany.Web.UserService.MarkNotificationAsReadRequest request) {
            return base.Channel.MarkNotificationAsReadAsync(request);
        }
        
        public System.Threading.Tasks.Task<TrainingCompany.Web.UserService.MarkNotificationAsReadResponse> MarkNotificationAsReadAsync(int notificationId) {
            TrainingCompany.Web.UserService.MarkNotificationAsReadRequest inValue = new TrainingCompany.Web.UserService.MarkNotificationAsReadRequest();
            inValue.Body = new TrainingCompany.Web.UserService.MarkNotificationAsReadRequestBody();
            inValue.Body.notificationId = notificationId;
            return ((TrainingCompany.Web.UserService.UserServiceSoap)(this)).MarkNotificationAsReadAsync(inValue);
        }
    }
}
