//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrainingCompany.Web.TrainingServices {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Course", Namespace="http://trainingcompany.com/")]
    [System.SerializableAttribute()]
    public partial class Course : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int CourseIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TitleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        private int CategoryIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CategoryNameField;
        
        private decimal PriceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ScheduleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ModeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DurationField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ImageURLField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int CourseID {
            get {
                return this.CourseIDField;
            }
            set {
                if ((this.CourseIDField.Equals(value) != true)) {
                    this.CourseIDField = value;
                    this.RaisePropertyChanged("CourseID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Title {
            get {
                return this.TitleField;
            }
            set {
                if ((object.ReferenceEquals(this.TitleField, value) != true)) {
                    this.TitleField = value;
                    this.RaisePropertyChanged("Title");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public int CategoryID {
            get {
                return this.CategoryIDField;
            }
            set {
                if ((this.CategoryIDField.Equals(value) != true)) {
                    this.CategoryIDField = value;
                    this.RaisePropertyChanged("CategoryID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string CategoryName {
            get {
                return this.CategoryNameField;
            }
            set {
                if ((object.ReferenceEquals(this.CategoryNameField, value) != true)) {
                    this.CategoryNameField = value;
                    this.RaisePropertyChanged("CategoryName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=5)]
        public decimal Price {
            get {
                return this.PriceField;
            }
            set {
                if ((this.PriceField.Equals(value) != true)) {
                    this.PriceField = value;
                    this.RaisePropertyChanged("Price");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string Schedule {
            get {
                return this.ScheduleField;
            }
            set {
                if ((object.ReferenceEquals(this.ScheduleField, value) != true)) {
                    this.ScheduleField = value;
                    this.RaisePropertyChanged("Schedule");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string Mode {
            get {
                return this.ModeField;
            }
            set {
                if ((object.ReferenceEquals(this.ModeField, value) != true)) {
                    this.ModeField = value;
                    this.RaisePropertyChanged("Mode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public string Duration {
            get {
                return this.DurationField;
            }
            set {
                if ((object.ReferenceEquals(this.DurationField, value) != true)) {
                    this.DurationField = value;
                    this.RaisePropertyChanged("Duration");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=9)]
        public string ImageURL {
            get {
                return this.ImageURLField;
            }
            set {
                if ((object.ReferenceEquals(this.ImageURLField, value) != true)) {
                    this.ImageURLField = value;
                    this.RaisePropertyChanged("ImageURL");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ServiceResponse", Namespace="http://trainingcompany.com/")]
    [System.SerializableAttribute()]
    public partial class ServiceResponse : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private bool SuccessField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DataField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public bool Success {
            get {
                return this.SuccessField;
            }
            set {
                if ((this.SuccessField.Equals(value) != true)) {
                    this.SuccessField = value;
                    this.RaisePropertyChanged("Success");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Message {
            get {
                return this.MessageField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageField, value) != true)) {
                    this.MessageField = value;
                    this.RaisePropertyChanged("Message");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Data {
            get {
                return this.DataField;
            }
            set {
                if ((object.ReferenceEquals(this.DataField, value) != true)) {
                    this.DataField = value;
                    this.RaisePropertyChanged("Data");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FAQ", Namespace="http://trainingcompany.com/")]
    [System.SerializableAttribute()]
    public partial class FAQ : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int FAQIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string QuestionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AnswerField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IntentTagField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string KeywordsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CategoryField;
        
        private int PriorityField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int FAQID {
            get {
                return this.FAQIDField;
            }
            set {
                if ((this.FAQIDField.Equals(value) != true)) {
                    this.FAQIDField = value;
                    this.RaisePropertyChanged("FAQID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Question {
            get {
                return this.QuestionField;
            }
            set {
                if ((object.ReferenceEquals(this.QuestionField, value) != true)) {
                    this.QuestionField = value;
                    this.RaisePropertyChanged("Question");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Answer {
            get {
                return this.AnswerField;
            }
            set {
                if ((object.ReferenceEquals(this.AnswerField, value) != true)) {
                    this.AnswerField = value;
                    this.RaisePropertyChanged("Answer");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string IntentTag {
            get {
                return this.IntentTagField;
            }
            set {
                if ((object.ReferenceEquals(this.IntentTagField, value) != true)) {
                    this.IntentTagField = value;
                    this.RaisePropertyChanged("IntentTag");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string Keywords {
            get {
                return this.KeywordsField;
            }
            set {
                if ((object.ReferenceEquals(this.KeywordsField, value) != true)) {
                    this.KeywordsField = value;
                    this.RaisePropertyChanged("Keywords");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string Category {
            get {
                return this.CategoryField;
            }
            set {
                if ((object.ReferenceEquals(this.CategoryField, value) != true)) {
                    this.CategoryField = value;
                    this.RaisePropertyChanged("Category");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=6)]
        public int Priority {
            get {
                return this.PriorityField;
            }
            set {
                if ((this.PriorityField.Equals(value) != true)) {
                    this.PriorityField = value;
                    this.RaisePropertyChanged("Priority");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Category", Namespace="http://trainingcompany.com/")]
    [System.SerializableAttribute()]
    public partial class Category : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int CategoryIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CategoryNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int CategoryID {
            get {
                return this.CategoryIDField;
            }
            set {
                if ((this.CategoryIDField.Equals(value) != true)) {
                    this.CategoryIDField = value;
                    this.RaisePropertyChanged("CategoryID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string CategoryName {
            get {
                return this.CategoryNameField;
            }
            set {
                if ((object.ReferenceEquals(this.CategoryNameField, value) != true)) {
                    this.CategoryNameField = value;
                    this.RaisePropertyChanged("CategoryName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://trainingcompany.com/", ConfigurationName="TrainingServices.AdminServiceSoap")]
    public interface AdminServiceSoap {
        
        // CODEGEN: Generating message contract since element name course from namespace http://trainingcompany.com/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://trainingcompany.com/AddCourse", ReplyAction="*")]
        TrainingCompany.Web.TrainingServices.AddCourseResponse AddCourse(TrainingCompany.Web.TrainingServices.AddCourseRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://trainingcompany.com/AddCourse", ReplyAction="*")]
        System.Threading.Tasks.Task<TrainingCompany.Web.TrainingServices.AddCourseResponse> AddCourseAsync(TrainingCompany.Web.TrainingServices.AddCourseRequest request);
        
        // CODEGEN: Generating message contract since element name course from namespace http://trainingcompany.com/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://trainingcompany.com/UpdateCourse", ReplyAction="*")]
        TrainingCompany.Web.TrainingServices.UpdateCourseResponse UpdateCourse(TrainingCompany.Web.TrainingServices.UpdateCourseRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://trainingcompany.com/UpdateCourse", ReplyAction="*")]
        System.Threading.Tasks.Task<TrainingCompany.Web.TrainingServices.UpdateCourseResponse> UpdateCourseAsync(TrainingCompany.Web.TrainingServices.UpdateCourseRequest request);
        
        // CODEGEN: Generating message contract since element name DeleteCourseResult from namespace http://trainingcompany.com/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://trainingcompany.com/DeleteCourse", ReplyAction="*")]
        TrainingCompany.Web.TrainingServices.DeleteCourseResponse DeleteCourse(TrainingCompany.Web.TrainingServices.DeleteCourseRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://trainingcompany.com/DeleteCourse", ReplyAction="*")]
        System.Threading.Tasks.Task<TrainingCompany.Web.TrainingServices.DeleteCourseResponse> DeleteCourseAsync(TrainingCompany.Web.TrainingServices.DeleteCourseRequest request);
        
        // CODEGEN: Generating message contract since element name GetAllCoursesResult from namespace http://trainingcompany.com/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://trainingcompany.com/GetAllCourses", ReplyAction="*")]
        TrainingCompany.Web.TrainingServices.GetAllCoursesResponse GetAllCourses(TrainingCompany.Web.TrainingServices.GetAllCoursesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://trainingcompany.com/GetAllCourses", ReplyAction="*")]
        System.Threading.Tasks.Task<TrainingCompany.Web.TrainingServices.GetAllCoursesResponse> GetAllCoursesAsync(TrainingCompany.Web.TrainingServices.GetAllCoursesRequest request);
        
        // CODEGEN: Generating message contract since element name GetCourseByIdResult from namespace http://trainingcompany.com/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://trainingcompany.com/GetCourseById", ReplyAction="*")]
        TrainingCompany.Web.TrainingServices.GetCourseByIdResponse GetCourseById(TrainingCompany.Web.TrainingServices.GetCourseByIdRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://trainingcompany.com/GetCourseById", ReplyAction="*")]
        System.Threading.Tasks.Task<TrainingCompany.Web.TrainingServices.GetCourseByIdResponse> GetCourseByIdAsync(TrainingCompany.Web.TrainingServices.GetCourseByIdRequest request);
        
        // CODEGEN: Generating message contract since element name faq from namespace http://trainingcompany.com/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://trainingcompany.com/AddFAQ", ReplyAction="*")]
        TrainingCompany.Web.TrainingServices.AddFAQResponse AddFAQ(TrainingCompany.Web.TrainingServices.AddFAQRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://trainingcompany.com/AddFAQ", ReplyAction="*")]
        System.Threading.Tasks.Task<TrainingCompany.Web.TrainingServices.AddFAQResponse> AddFAQAsync(TrainingCompany.Web.TrainingServices.AddFAQRequest request);
        
        // CODEGEN: Generating message contract since element name faq from namespace http://trainingcompany.com/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://trainingcompany.com/UpdateFAQ", ReplyAction="*")]
        TrainingCompany.Web.TrainingServices.UpdateFAQResponse UpdateFAQ(TrainingCompany.Web.TrainingServices.UpdateFAQRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://trainingcompany.com/UpdateFAQ", ReplyAction="*")]
        System.Threading.Tasks.Task<TrainingCompany.Web.TrainingServices.UpdateFAQResponse> UpdateFAQAsync(TrainingCompany.Web.TrainingServices.UpdateFAQRequest request);
        
        // CODEGEN: Generating message contract since element name DeleteFAQResult from namespace http://trainingcompany.com/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://trainingcompany.com/DeleteFAQ", ReplyAction="*")]
        TrainingCompany.Web.TrainingServices.DeleteFAQResponse DeleteFAQ(TrainingCompany.Web.TrainingServices.DeleteFAQRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://trainingcompany.com/DeleteFAQ", ReplyAction="*")]
        System.Threading.Tasks.Task<TrainingCompany.Web.TrainingServices.DeleteFAQResponse> DeleteFAQAsync(TrainingCompany.Web.TrainingServices.DeleteFAQRequest request);
        
        // CODEGEN: Generating message contract since element name GetAllFAQsResult from namespace http://trainingcompany.com/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://trainingcompany.com/GetAllFAQs", ReplyAction="*")]
        TrainingCompany.Web.TrainingServices.GetAllFAQsResponse GetAllFAQs(TrainingCompany.Web.TrainingServices.GetAllFAQsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://trainingcompany.com/GetAllFAQs", ReplyAction="*")]
        System.Threading.Tasks.Task<TrainingCompany.Web.TrainingServices.GetAllFAQsResponse> GetAllFAQsAsync(TrainingCompany.Web.TrainingServices.GetAllFAQsRequest request);
        
        // CODEGEN: Generating message contract since element name TestConnectionResult from namespace http://trainingcompany.com/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://trainingcompany.com/TestConnection", ReplyAction="*")]
        TrainingCompany.Web.TrainingServices.TestConnectionResponse TestConnection(TrainingCompany.Web.TrainingServices.TestConnectionRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://trainingcompany.com/TestConnection", ReplyAction="*")]
        System.Threading.Tasks.Task<TrainingCompany.Web.TrainingServices.TestConnectionResponse> TestConnectionAsync(TrainingCompany.Web.TrainingServices.TestConnectionRequest request);
        
        // CODEGEN: Generating message contract since element name GetAllCategoriesResult from namespace http://trainingcompany.com/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://trainingcompany.com/GetAllCategories", ReplyAction="*")]
        TrainingCompany.Web.TrainingServices.GetAllCategoriesResponse GetAllCategories(TrainingCompany.Web.TrainingServices.GetAllCategoriesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://trainingcompany.com/GetAllCategories", ReplyAction="*")]
        System.Threading.Tasks.Task<TrainingCompany.Web.TrainingServices.GetAllCategoriesResponse> GetAllCategoriesAsync(TrainingCompany.Web.TrainingServices.GetAllCategoriesRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddCourseRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddCourse", Namespace="http://trainingcompany.com/", Order=0)]
        public TrainingCompany.Web.TrainingServices.AddCourseRequestBody Body;
        
        public AddCourseRequest() {
        }
        
        public AddCourseRequest(TrainingCompany.Web.TrainingServices.AddCourseRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://trainingcompany.com/")]
    public partial class AddCourseRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public TrainingCompany.Web.TrainingServices.Course course;
        
        public AddCourseRequestBody() {
        }
        
        public AddCourseRequestBody(TrainingCompany.Web.TrainingServices.Course course) {
            this.course = course;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddCourseResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddCourseResponse", Namespace="http://trainingcompany.com/", Order=0)]
        public TrainingCompany.Web.TrainingServices.AddCourseResponseBody Body;
        
        public AddCourseResponse() {
        }
        
        public AddCourseResponse(TrainingCompany.Web.TrainingServices.AddCourseResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://trainingcompany.com/")]
    public partial class AddCourseResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public TrainingCompany.Web.TrainingServices.ServiceResponse AddCourseResult;
        
        public AddCourseResponseBody() {
        }
        
        public AddCourseResponseBody(TrainingCompany.Web.TrainingServices.ServiceResponse AddCourseResult) {
            this.AddCourseResult = AddCourseResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateCourseRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateCourse", Namespace="http://trainingcompany.com/", Order=0)]
        public TrainingCompany.Web.TrainingServices.UpdateCourseRequestBody Body;
        
        public UpdateCourseRequest() {
        }
        
        public UpdateCourseRequest(TrainingCompany.Web.TrainingServices.UpdateCourseRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://trainingcompany.com/")]
    public partial class UpdateCourseRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public TrainingCompany.Web.TrainingServices.Course course;
        
        public UpdateCourseRequestBody() {
        }
        
        public UpdateCourseRequestBody(TrainingCompany.Web.TrainingServices.Course course) {
            this.course = course;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateCourseResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateCourseResponse", Namespace="http://trainingcompany.com/", Order=0)]
        public TrainingCompany.Web.TrainingServices.UpdateCourseResponseBody Body;
        
        public UpdateCourseResponse() {
        }
        
        public UpdateCourseResponse(TrainingCompany.Web.TrainingServices.UpdateCourseResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://trainingcompany.com/")]
    public partial class UpdateCourseResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public TrainingCompany.Web.TrainingServices.ServiceResponse UpdateCourseResult;
        
        public UpdateCourseResponseBody() {
        }
        
        public UpdateCourseResponseBody(TrainingCompany.Web.TrainingServices.ServiceResponse UpdateCourseResult) {
            this.UpdateCourseResult = UpdateCourseResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DeleteCourseRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DeleteCourse", Namespace="http://trainingcompany.com/", Order=0)]
        public TrainingCompany.Web.TrainingServices.DeleteCourseRequestBody Body;
        
        public DeleteCourseRequest() {
        }
        
        public DeleteCourseRequest(TrainingCompany.Web.TrainingServices.DeleteCourseRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://trainingcompany.com/")]
    public partial class DeleteCourseRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int courseId;
        
        public DeleteCourseRequestBody() {
        }
        
        public DeleteCourseRequestBody(int courseId) {
            this.courseId = courseId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DeleteCourseResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DeleteCourseResponse", Namespace="http://trainingcompany.com/", Order=0)]
        public TrainingCompany.Web.TrainingServices.DeleteCourseResponseBody Body;
        
        public DeleteCourseResponse() {
        }
        
        public DeleteCourseResponse(TrainingCompany.Web.TrainingServices.DeleteCourseResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://trainingcompany.com/")]
    public partial class DeleteCourseResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public TrainingCompany.Web.TrainingServices.ServiceResponse DeleteCourseResult;
        
        public DeleteCourseResponseBody() {
        }
        
        public DeleteCourseResponseBody(TrainingCompany.Web.TrainingServices.ServiceResponse DeleteCourseResult) {
            this.DeleteCourseResult = DeleteCourseResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAllCoursesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAllCourses", Namespace="http://trainingcompany.com/", Order=0)]
        public TrainingCompany.Web.TrainingServices.GetAllCoursesRequestBody Body;
        
        public GetAllCoursesRequest() {
        }
        
        public GetAllCoursesRequest(TrainingCompany.Web.TrainingServices.GetAllCoursesRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetAllCoursesRequestBody {
        
        public GetAllCoursesRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAllCoursesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAllCoursesResponse", Namespace="http://trainingcompany.com/", Order=0)]
        public TrainingCompany.Web.TrainingServices.GetAllCoursesResponseBody Body;
        
        public GetAllCoursesResponse() {
        }
        
        public GetAllCoursesResponse(TrainingCompany.Web.TrainingServices.GetAllCoursesResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://trainingcompany.com/")]
    public partial class GetAllCoursesResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public TrainingCompany.Web.TrainingServices.Course[] GetAllCoursesResult;
        
        public GetAllCoursesResponseBody() {
        }
        
        public GetAllCoursesResponseBody(TrainingCompany.Web.TrainingServices.Course[] GetAllCoursesResult) {
            this.GetAllCoursesResult = GetAllCoursesResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetCourseByIdRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetCourseById", Namespace="http://trainingcompany.com/", Order=0)]
        public TrainingCompany.Web.TrainingServices.GetCourseByIdRequestBody Body;
        
        public GetCourseByIdRequest() {
        }
        
        public GetCourseByIdRequest(TrainingCompany.Web.TrainingServices.GetCourseByIdRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://trainingcompany.com/")]
    public partial class GetCourseByIdRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int courseId;
        
        public GetCourseByIdRequestBody() {
        }
        
        public GetCourseByIdRequestBody(int courseId) {
            this.courseId = courseId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetCourseByIdResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetCourseByIdResponse", Namespace="http://trainingcompany.com/", Order=0)]
        public TrainingCompany.Web.TrainingServices.GetCourseByIdResponseBody Body;
        
        public GetCourseByIdResponse() {
        }
        
        public GetCourseByIdResponse(TrainingCompany.Web.TrainingServices.GetCourseByIdResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://trainingcompany.com/")]
    public partial class GetCourseByIdResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public TrainingCompany.Web.TrainingServices.Course GetCourseByIdResult;
        
        public GetCourseByIdResponseBody() {
        }
        
        public GetCourseByIdResponseBody(TrainingCompany.Web.TrainingServices.Course GetCourseByIdResult) {
            this.GetCourseByIdResult = GetCourseByIdResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddFAQRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddFAQ", Namespace="http://trainingcompany.com/", Order=0)]
        public TrainingCompany.Web.TrainingServices.AddFAQRequestBody Body;
        
        public AddFAQRequest() {
        }
        
        public AddFAQRequest(TrainingCompany.Web.TrainingServices.AddFAQRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://trainingcompany.com/")]
    public partial class AddFAQRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public TrainingCompany.Web.TrainingServices.FAQ faq;
        
        public AddFAQRequestBody() {
        }
        
        public AddFAQRequestBody(TrainingCompany.Web.TrainingServices.FAQ faq) {
            this.faq = faq;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddFAQResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddFAQResponse", Namespace="http://trainingcompany.com/", Order=0)]
        public TrainingCompany.Web.TrainingServices.AddFAQResponseBody Body;
        
        public AddFAQResponse() {
        }
        
        public AddFAQResponse(TrainingCompany.Web.TrainingServices.AddFAQResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://trainingcompany.com/")]
    public partial class AddFAQResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public TrainingCompany.Web.TrainingServices.ServiceResponse AddFAQResult;
        
        public AddFAQResponseBody() {
        }
        
        public AddFAQResponseBody(TrainingCompany.Web.TrainingServices.ServiceResponse AddFAQResult) {
            this.AddFAQResult = AddFAQResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateFAQRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateFAQ", Namespace="http://trainingcompany.com/", Order=0)]
        public TrainingCompany.Web.TrainingServices.UpdateFAQRequestBody Body;
        
        public UpdateFAQRequest() {
        }
        
        public UpdateFAQRequest(TrainingCompany.Web.TrainingServices.UpdateFAQRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://trainingcompany.com/")]
    public partial class UpdateFAQRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public TrainingCompany.Web.TrainingServices.FAQ faq;
        
        public UpdateFAQRequestBody() {
        }
        
        public UpdateFAQRequestBody(TrainingCompany.Web.TrainingServices.FAQ faq) {
            this.faq = faq;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateFAQResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateFAQResponse", Namespace="http://trainingcompany.com/", Order=0)]
        public TrainingCompany.Web.TrainingServices.UpdateFAQResponseBody Body;
        
        public UpdateFAQResponse() {
        }
        
        public UpdateFAQResponse(TrainingCompany.Web.TrainingServices.UpdateFAQResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://trainingcompany.com/")]
    public partial class UpdateFAQResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public TrainingCompany.Web.TrainingServices.ServiceResponse UpdateFAQResult;
        
        public UpdateFAQResponseBody() {
        }
        
        public UpdateFAQResponseBody(TrainingCompany.Web.TrainingServices.ServiceResponse UpdateFAQResult) {
            this.UpdateFAQResult = UpdateFAQResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DeleteFAQRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DeleteFAQ", Namespace="http://trainingcompany.com/", Order=0)]
        public TrainingCompany.Web.TrainingServices.DeleteFAQRequestBody Body;
        
        public DeleteFAQRequest() {
        }
        
        public DeleteFAQRequest(TrainingCompany.Web.TrainingServices.DeleteFAQRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://trainingcompany.com/")]
    public partial class DeleteFAQRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int faqId;
        
        public DeleteFAQRequestBody() {
        }
        
        public DeleteFAQRequestBody(int faqId) {
            this.faqId = faqId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DeleteFAQResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DeleteFAQResponse", Namespace="http://trainingcompany.com/", Order=0)]
        public TrainingCompany.Web.TrainingServices.DeleteFAQResponseBody Body;
        
        public DeleteFAQResponse() {
        }
        
        public DeleteFAQResponse(TrainingCompany.Web.TrainingServices.DeleteFAQResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://trainingcompany.com/")]
    public partial class DeleteFAQResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public TrainingCompany.Web.TrainingServices.ServiceResponse DeleteFAQResult;
        
        public DeleteFAQResponseBody() {
        }
        
        public DeleteFAQResponseBody(TrainingCompany.Web.TrainingServices.ServiceResponse DeleteFAQResult) {
            this.DeleteFAQResult = DeleteFAQResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAllFAQsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAllFAQs", Namespace="http://trainingcompany.com/", Order=0)]
        public TrainingCompany.Web.TrainingServices.GetAllFAQsRequestBody Body;
        
        public GetAllFAQsRequest() {
        }
        
        public GetAllFAQsRequest(TrainingCompany.Web.TrainingServices.GetAllFAQsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetAllFAQsRequestBody {
        
        public GetAllFAQsRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAllFAQsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAllFAQsResponse", Namespace="http://trainingcompany.com/", Order=0)]
        public TrainingCompany.Web.TrainingServices.GetAllFAQsResponseBody Body;
        
        public GetAllFAQsResponse() {
        }
        
        public GetAllFAQsResponse(TrainingCompany.Web.TrainingServices.GetAllFAQsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://trainingcompany.com/")]
    public partial class GetAllFAQsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public TrainingCompany.Web.TrainingServices.FAQ[] GetAllFAQsResult;
        
        public GetAllFAQsResponseBody() {
        }
        
        public GetAllFAQsResponseBody(TrainingCompany.Web.TrainingServices.FAQ[] GetAllFAQsResult) {
            this.GetAllFAQsResult = GetAllFAQsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class TestConnectionRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="TestConnection", Namespace="http://trainingcompany.com/", Order=0)]
        public TrainingCompany.Web.TrainingServices.TestConnectionRequestBody Body;
        
        public TestConnectionRequest() {
        }
        
        public TestConnectionRequest(TrainingCompany.Web.TrainingServices.TestConnectionRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class TestConnectionRequestBody {
        
        public TestConnectionRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class TestConnectionResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="TestConnectionResponse", Namespace="http://trainingcompany.com/", Order=0)]
        public TrainingCompany.Web.TrainingServices.TestConnectionResponseBody Body;
        
        public TestConnectionResponse() {
        }
        
        public TestConnectionResponse(TrainingCompany.Web.TrainingServices.TestConnectionResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://trainingcompany.com/")]
    public partial class TestConnectionResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string TestConnectionResult;
        
        public TestConnectionResponseBody() {
        }
        
        public TestConnectionResponseBody(string TestConnectionResult) {
            this.TestConnectionResult = TestConnectionResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAllCategoriesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAllCategories", Namespace="http://trainingcompany.com/", Order=0)]
        public TrainingCompany.Web.TrainingServices.GetAllCategoriesRequestBody Body;
        
        public GetAllCategoriesRequest() {
        }
        
        public GetAllCategoriesRequest(TrainingCompany.Web.TrainingServices.GetAllCategoriesRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetAllCategoriesRequestBody {
        
        public GetAllCategoriesRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAllCategoriesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAllCategoriesResponse", Namespace="http://trainingcompany.com/", Order=0)]
        public TrainingCompany.Web.TrainingServices.GetAllCategoriesResponseBody Body;
        
        public GetAllCategoriesResponse() {
        }
        
        public GetAllCategoriesResponse(TrainingCompany.Web.TrainingServices.GetAllCategoriesResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://trainingcompany.com/")]
    public partial class GetAllCategoriesResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public TrainingCompany.Web.TrainingServices.Category[] GetAllCategoriesResult;
        
        public GetAllCategoriesResponseBody() {
        }
        
        public GetAllCategoriesResponseBody(TrainingCompany.Web.TrainingServices.Category[] GetAllCategoriesResult) {
            this.GetAllCategoriesResult = GetAllCategoriesResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface AdminServiceSoapChannel : TrainingCompany.Web.TrainingServices.AdminServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AdminServiceSoapClient : System.ServiceModel.ClientBase<TrainingCompany.Web.TrainingServices.AdminServiceSoap>, TrainingCompany.Web.TrainingServices.AdminServiceSoap {
        
        public AdminServiceSoapClient() {
        }
        
        public AdminServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public AdminServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AdminServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AdminServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TrainingCompany.Web.TrainingServices.AddCourseResponse TrainingCompany.Web.TrainingServices.AdminServiceSoap.AddCourse(TrainingCompany.Web.TrainingServices.AddCourseRequest request) {
            return base.Channel.AddCourse(request);
        }
        
        public TrainingCompany.Web.TrainingServices.ServiceResponse AddCourse(TrainingCompany.Web.TrainingServices.Course course) {
            TrainingCompany.Web.TrainingServices.AddCourseRequest inValue = new TrainingCompany.Web.TrainingServices.AddCourseRequest();
            inValue.Body = new TrainingCompany.Web.TrainingServices.AddCourseRequestBody();
            inValue.Body.course = course;
            TrainingCompany.Web.TrainingServices.AddCourseResponse retVal = ((TrainingCompany.Web.TrainingServices.AdminServiceSoap)(this)).AddCourse(inValue);
            return retVal.Body.AddCourseResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TrainingCompany.Web.TrainingServices.AddCourseResponse> TrainingCompany.Web.TrainingServices.AdminServiceSoap.AddCourseAsync(TrainingCompany.Web.TrainingServices.AddCourseRequest request) {
            return base.Channel.AddCourseAsync(request);
        }
        
        public System.Threading.Tasks.Task<TrainingCompany.Web.TrainingServices.AddCourseResponse> AddCourseAsync(TrainingCompany.Web.TrainingServices.Course course) {
            TrainingCompany.Web.TrainingServices.AddCourseRequest inValue = new TrainingCompany.Web.TrainingServices.AddCourseRequest();
            inValue.Body = new TrainingCompany.Web.TrainingServices.AddCourseRequestBody();
            inValue.Body.course = course;
            return ((TrainingCompany.Web.TrainingServices.AdminServiceSoap)(this)).AddCourseAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TrainingCompany.Web.TrainingServices.UpdateCourseResponse TrainingCompany.Web.TrainingServices.AdminServiceSoap.UpdateCourse(TrainingCompany.Web.TrainingServices.UpdateCourseRequest request) {
            return base.Channel.UpdateCourse(request);
        }
        
        public TrainingCompany.Web.TrainingServices.ServiceResponse UpdateCourse(TrainingCompany.Web.TrainingServices.Course course) {
            TrainingCompany.Web.TrainingServices.UpdateCourseRequest inValue = new TrainingCompany.Web.TrainingServices.UpdateCourseRequest();
            inValue.Body = new TrainingCompany.Web.TrainingServices.UpdateCourseRequestBody();
            inValue.Body.course = course;
            TrainingCompany.Web.TrainingServices.UpdateCourseResponse retVal = ((TrainingCompany.Web.TrainingServices.AdminServiceSoap)(this)).UpdateCourse(inValue);
            return retVal.Body.UpdateCourseResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TrainingCompany.Web.TrainingServices.UpdateCourseResponse> TrainingCompany.Web.TrainingServices.AdminServiceSoap.UpdateCourseAsync(TrainingCompany.Web.TrainingServices.UpdateCourseRequest request) {
            return base.Channel.UpdateCourseAsync(request);
        }
        
        public System.Threading.Tasks.Task<TrainingCompany.Web.TrainingServices.UpdateCourseResponse> UpdateCourseAsync(TrainingCompany.Web.TrainingServices.Course course) {
            TrainingCompany.Web.TrainingServices.UpdateCourseRequest inValue = new TrainingCompany.Web.TrainingServices.UpdateCourseRequest();
            inValue.Body = new TrainingCompany.Web.TrainingServices.UpdateCourseRequestBody();
            inValue.Body.course = course;
            return ((TrainingCompany.Web.TrainingServices.AdminServiceSoap)(this)).UpdateCourseAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TrainingCompany.Web.TrainingServices.DeleteCourseResponse TrainingCompany.Web.TrainingServices.AdminServiceSoap.DeleteCourse(TrainingCompany.Web.TrainingServices.DeleteCourseRequest request) {
            return base.Channel.DeleteCourse(request);
        }
        
        public TrainingCompany.Web.TrainingServices.ServiceResponse DeleteCourse(int courseId) {
            TrainingCompany.Web.TrainingServices.DeleteCourseRequest inValue = new TrainingCompany.Web.TrainingServices.DeleteCourseRequest();
            inValue.Body = new TrainingCompany.Web.TrainingServices.DeleteCourseRequestBody();
            inValue.Body.courseId = courseId;
            TrainingCompany.Web.TrainingServices.DeleteCourseResponse retVal = ((TrainingCompany.Web.TrainingServices.AdminServiceSoap)(this)).DeleteCourse(inValue);
            return retVal.Body.DeleteCourseResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TrainingCompany.Web.TrainingServices.DeleteCourseResponse> TrainingCompany.Web.TrainingServices.AdminServiceSoap.DeleteCourseAsync(TrainingCompany.Web.TrainingServices.DeleteCourseRequest request) {
            return base.Channel.DeleteCourseAsync(request);
        }
        
        public System.Threading.Tasks.Task<TrainingCompany.Web.TrainingServices.DeleteCourseResponse> DeleteCourseAsync(int courseId) {
            TrainingCompany.Web.TrainingServices.DeleteCourseRequest inValue = new TrainingCompany.Web.TrainingServices.DeleteCourseRequest();
            inValue.Body = new TrainingCompany.Web.TrainingServices.DeleteCourseRequestBody();
            inValue.Body.courseId = courseId;
            return ((TrainingCompany.Web.TrainingServices.AdminServiceSoap)(this)).DeleteCourseAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TrainingCompany.Web.TrainingServices.GetAllCoursesResponse TrainingCompany.Web.TrainingServices.AdminServiceSoap.GetAllCourses(TrainingCompany.Web.TrainingServices.GetAllCoursesRequest request) {
            return base.Channel.GetAllCourses(request);
        }
        
        public TrainingCompany.Web.TrainingServices.Course[] GetAllCourses() {
            TrainingCompany.Web.TrainingServices.GetAllCoursesRequest inValue = new TrainingCompany.Web.TrainingServices.GetAllCoursesRequest();
            inValue.Body = new TrainingCompany.Web.TrainingServices.GetAllCoursesRequestBody();
            TrainingCompany.Web.TrainingServices.GetAllCoursesResponse retVal = ((TrainingCompany.Web.TrainingServices.AdminServiceSoap)(this)).GetAllCourses(inValue);
            return retVal.Body.GetAllCoursesResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TrainingCompany.Web.TrainingServices.GetAllCoursesResponse> TrainingCompany.Web.TrainingServices.AdminServiceSoap.GetAllCoursesAsync(TrainingCompany.Web.TrainingServices.GetAllCoursesRequest request) {
            return base.Channel.GetAllCoursesAsync(request);
        }
        
        public System.Threading.Tasks.Task<TrainingCompany.Web.TrainingServices.GetAllCoursesResponse> GetAllCoursesAsync() {
            TrainingCompany.Web.TrainingServices.GetAllCoursesRequest inValue = new TrainingCompany.Web.TrainingServices.GetAllCoursesRequest();
            inValue.Body = new TrainingCompany.Web.TrainingServices.GetAllCoursesRequestBody();
            return ((TrainingCompany.Web.TrainingServices.AdminServiceSoap)(this)).GetAllCoursesAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TrainingCompany.Web.TrainingServices.GetCourseByIdResponse TrainingCompany.Web.TrainingServices.AdminServiceSoap.GetCourseById(TrainingCompany.Web.TrainingServices.GetCourseByIdRequest request) {
            return base.Channel.GetCourseById(request);
        }
        
        public TrainingCompany.Web.TrainingServices.Course GetCourseById(int courseId) {
            TrainingCompany.Web.TrainingServices.GetCourseByIdRequest inValue = new TrainingCompany.Web.TrainingServices.GetCourseByIdRequest();
            inValue.Body = new TrainingCompany.Web.TrainingServices.GetCourseByIdRequestBody();
            inValue.Body.courseId = courseId;
            TrainingCompany.Web.TrainingServices.GetCourseByIdResponse retVal = ((TrainingCompany.Web.TrainingServices.AdminServiceSoap)(this)).GetCourseById(inValue);
            return retVal.Body.GetCourseByIdResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TrainingCompany.Web.TrainingServices.GetCourseByIdResponse> TrainingCompany.Web.TrainingServices.AdminServiceSoap.GetCourseByIdAsync(TrainingCompany.Web.TrainingServices.GetCourseByIdRequest request) {
            return base.Channel.GetCourseByIdAsync(request);
        }
        
        public System.Threading.Tasks.Task<TrainingCompany.Web.TrainingServices.GetCourseByIdResponse> GetCourseByIdAsync(int courseId) {
            TrainingCompany.Web.TrainingServices.GetCourseByIdRequest inValue = new TrainingCompany.Web.TrainingServices.GetCourseByIdRequest();
            inValue.Body = new TrainingCompany.Web.TrainingServices.GetCourseByIdRequestBody();
            inValue.Body.courseId = courseId;
            return ((TrainingCompany.Web.TrainingServices.AdminServiceSoap)(this)).GetCourseByIdAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TrainingCompany.Web.TrainingServices.AddFAQResponse TrainingCompany.Web.TrainingServices.AdminServiceSoap.AddFAQ(TrainingCompany.Web.TrainingServices.AddFAQRequest request) {
            return base.Channel.AddFAQ(request);
        }
        
        public TrainingCompany.Web.TrainingServices.ServiceResponse AddFAQ(TrainingCompany.Web.TrainingServices.FAQ faq) {
            TrainingCompany.Web.TrainingServices.AddFAQRequest inValue = new TrainingCompany.Web.TrainingServices.AddFAQRequest();
            inValue.Body = new TrainingCompany.Web.TrainingServices.AddFAQRequestBody();
            inValue.Body.faq = faq;
            TrainingCompany.Web.TrainingServices.AddFAQResponse retVal = ((TrainingCompany.Web.TrainingServices.AdminServiceSoap)(this)).AddFAQ(inValue);
            return retVal.Body.AddFAQResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TrainingCompany.Web.TrainingServices.AddFAQResponse> TrainingCompany.Web.TrainingServices.AdminServiceSoap.AddFAQAsync(TrainingCompany.Web.TrainingServices.AddFAQRequest request) {
            return base.Channel.AddFAQAsync(request);
        }
        
        public System.Threading.Tasks.Task<TrainingCompany.Web.TrainingServices.AddFAQResponse> AddFAQAsync(TrainingCompany.Web.TrainingServices.FAQ faq) {
            TrainingCompany.Web.TrainingServices.AddFAQRequest inValue = new TrainingCompany.Web.TrainingServices.AddFAQRequest();
            inValue.Body = new TrainingCompany.Web.TrainingServices.AddFAQRequestBody();
            inValue.Body.faq = faq;
            return ((TrainingCompany.Web.TrainingServices.AdminServiceSoap)(this)).AddFAQAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TrainingCompany.Web.TrainingServices.UpdateFAQResponse TrainingCompany.Web.TrainingServices.AdminServiceSoap.UpdateFAQ(TrainingCompany.Web.TrainingServices.UpdateFAQRequest request) {
            return base.Channel.UpdateFAQ(request);
        }
        
        public TrainingCompany.Web.TrainingServices.ServiceResponse UpdateFAQ(TrainingCompany.Web.TrainingServices.FAQ faq) {
            TrainingCompany.Web.TrainingServices.UpdateFAQRequest inValue = new TrainingCompany.Web.TrainingServices.UpdateFAQRequest();
            inValue.Body = new TrainingCompany.Web.TrainingServices.UpdateFAQRequestBody();
            inValue.Body.faq = faq;
            TrainingCompany.Web.TrainingServices.UpdateFAQResponse retVal = ((TrainingCompany.Web.TrainingServices.AdminServiceSoap)(this)).UpdateFAQ(inValue);
            return retVal.Body.UpdateFAQResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TrainingCompany.Web.TrainingServices.UpdateFAQResponse> TrainingCompany.Web.TrainingServices.AdminServiceSoap.UpdateFAQAsync(TrainingCompany.Web.TrainingServices.UpdateFAQRequest request) {
            return base.Channel.UpdateFAQAsync(request);
        }
        
        public System.Threading.Tasks.Task<TrainingCompany.Web.TrainingServices.UpdateFAQResponse> UpdateFAQAsync(TrainingCompany.Web.TrainingServices.FAQ faq) {
            TrainingCompany.Web.TrainingServices.UpdateFAQRequest inValue = new TrainingCompany.Web.TrainingServices.UpdateFAQRequest();
            inValue.Body = new TrainingCompany.Web.TrainingServices.UpdateFAQRequestBody();
            inValue.Body.faq = faq;
            return ((TrainingCompany.Web.TrainingServices.AdminServiceSoap)(this)).UpdateFAQAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TrainingCompany.Web.TrainingServices.DeleteFAQResponse TrainingCompany.Web.TrainingServices.AdminServiceSoap.DeleteFAQ(TrainingCompany.Web.TrainingServices.DeleteFAQRequest request) {
            return base.Channel.DeleteFAQ(request);
        }
        
        public TrainingCompany.Web.TrainingServices.ServiceResponse DeleteFAQ(int faqId) {
            TrainingCompany.Web.TrainingServices.DeleteFAQRequest inValue = new TrainingCompany.Web.TrainingServices.DeleteFAQRequest();
            inValue.Body = new TrainingCompany.Web.TrainingServices.DeleteFAQRequestBody();
            inValue.Body.faqId = faqId;
            TrainingCompany.Web.TrainingServices.DeleteFAQResponse retVal = ((TrainingCompany.Web.TrainingServices.AdminServiceSoap)(this)).DeleteFAQ(inValue);
            return retVal.Body.DeleteFAQResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TrainingCompany.Web.TrainingServices.DeleteFAQResponse> TrainingCompany.Web.TrainingServices.AdminServiceSoap.DeleteFAQAsync(TrainingCompany.Web.TrainingServices.DeleteFAQRequest request) {
            return base.Channel.DeleteFAQAsync(request);
        }
        
        public System.Threading.Tasks.Task<TrainingCompany.Web.TrainingServices.DeleteFAQResponse> DeleteFAQAsync(int faqId) {
            TrainingCompany.Web.TrainingServices.DeleteFAQRequest inValue = new TrainingCompany.Web.TrainingServices.DeleteFAQRequest();
            inValue.Body = new TrainingCompany.Web.TrainingServices.DeleteFAQRequestBody();
            inValue.Body.faqId = faqId;
            return ((TrainingCompany.Web.TrainingServices.AdminServiceSoap)(this)).DeleteFAQAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TrainingCompany.Web.TrainingServices.GetAllFAQsResponse TrainingCompany.Web.TrainingServices.AdminServiceSoap.GetAllFAQs(TrainingCompany.Web.TrainingServices.GetAllFAQsRequest request) {
            return base.Channel.GetAllFAQs(request);
        }
        
        public TrainingCompany.Web.TrainingServices.FAQ[] GetAllFAQs() {
            TrainingCompany.Web.TrainingServices.GetAllFAQsRequest inValue = new TrainingCompany.Web.TrainingServices.GetAllFAQsRequest();
            inValue.Body = new TrainingCompany.Web.TrainingServices.GetAllFAQsRequestBody();
            TrainingCompany.Web.TrainingServices.GetAllFAQsResponse retVal = ((TrainingCompany.Web.TrainingServices.AdminServiceSoap)(this)).GetAllFAQs(inValue);
            return retVal.Body.GetAllFAQsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TrainingCompany.Web.TrainingServices.GetAllFAQsResponse> TrainingCompany.Web.TrainingServices.AdminServiceSoap.GetAllFAQsAsync(TrainingCompany.Web.TrainingServices.GetAllFAQsRequest request) {
            return base.Channel.GetAllFAQsAsync(request);
        }
        
        public System.Threading.Tasks.Task<TrainingCompany.Web.TrainingServices.GetAllFAQsResponse> GetAllFAQsAsync() {
            TrainingCompany.Web.TrainingServices.GetAllFAQsRequest inValue = new TrainingCompany.Web.TrainingServices.GetAllFAQsRequest();
            inValue.Body = new TrainingCompany.Web.TrainingServices.GetAllFAQsRequestBody();
            return ((TrainingCompany.Web.TrainingServices.AdminServiceSoap)(this)).GetAllFAQsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TrainingCompany.Web.TrainingServices.TestConnectionResponse TrainingCompany.Web.TrainingServices.AdminServiceSoap.TestConnection(TrainingCompany.Web.TrainingServices.TestConnectionRequest request) {
            return base.Channel.TestConnection(request);
        }
        
        public string TestConnection() {
            TrainingCompany.Web.TrainingServices.TestConnectionRequest inValue = new TrainingCompany.Web.TrainingServices.TestConnectionRequest();
            inValue.Body = new TrainingCompany.Web.TrainingServices.TestConnectionRequestBody();
            TrainingCompany.Web.TrainingServices.TestConnectionResponse retVal = ((TrainingCompany.Web.TrainingServices.AdminServiceSoap)(this)).TestConnection(inValue);
            return retVal.Body.TestConnectionResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TrainingCompany.Web.TrainingServices.TestConnectionResponse> TrainingCompany.Web.TrainingServices.AdminServiceSoap.TestConnectionAsync(TrainingCompany.Web.TrainingServices.TestConnectionRequest request) {
            return base.Channel.TestConnectionAsync(request);
        }
        
        public System.Threading.Tasks.Task<TrainingCompany.Web.TrainingServices.TestConnectionResponse> TestConnectionAsync() {
            TrainingCompany.Web.TrainingServices.TestConnectionRequest inValue = new TrainingCompany.Web.TrainingServices.TestConnectionRequest();
            inValue.Body = new TrainingCompany.Web.TrainingServices.TestConnectionRequestBody();
            return ((TrainingCompany.Web.TrainingServices.AdminServiceSoap)(this)).TestConnectionAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TrainingCompany.Web.TrainingServices.GetAllCategoriesResponse TrainingCompany.Web.TrainingServices.AdminServiceSoap.GetAllCategories(TrainingCompany.Web.TrainingServices.GetAllCategoriesRequest request) {
            return base.Channel.GetAllCategories(request);
        }
        
        public TrainingCompany.Web.TrainingServices.Category[] GetAllCategories() {
            TrainingCompany.Web.TrainingServices.GetAllCategoriesRequest inValue = new TrainingCompany.Web.TrainingServices.GetAllCategoriesRequest();
            inValue.Body = new TrainingCompany.Web.TrainingServices.GetAllCategoriesRequestBody();
            TrainingCompany.Web.TrainingServices.GetAllCategoriesResponse retVal = ((TrainingCompany.Web.TrainingServices.AdminServiceSoap)(this)).GetAllCategories(inValue);
            return retVal.Body.GetAllCategoriesResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TrainingCompany.Web.TrainingServices.GetAllCategoriesResponse> TrainingCompany.Web.TrainingServices.AdminServiceSoap.GetAllCategoriesAsync(TrainingCompany.Web.TrainingServices.GetAllCategoriesRequest request) {
            return base.Channel.GetAllCategoriesAsync(request);
        }
        
        public System.Threading.Tasks.Task<TrainingCompany.Web.TrainingServices.GetAllCategoriesResponse> GetAllCategoriesAsync() {
            TrainingCompany.Web.TrainingServices.GetAllCategoriesRequest inValue = new TrainingCompany.Web.TrainingServices.GetAllCategoriesRequest();
            inValue.Body = new TrainingCompany.Web.TrainingServices.GetAllCategoriesRequestBody();
            return ((TrainingCompany.Web.TrainingServices.AdminServiceSoap)(this)).GetAllCategoriesAsync(inValue);
        }
    }
}
